import { AchievementDef } from './achievements.js';

export const EXPANDED_EXPLICIT_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'ach_exp_1',
    title: 'Achievement Challenge Level #1',
    description: 'Complete match milestone challenge #1 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 5,
    rewardCoins: 200,
    rewardGems: 5,
    rewardXP: 50,
  },
  {
    id: 'ach_exp_2',
    title: 'Achievement Challenge Level #2',
    description: 'Complete match milestone challenge #2 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 10,
    rewardCoins: 400,
    rewardGems: 10,
    rewardXP: 100,
  },
  {
    id: 'ach_exp_3',
    title: 'Achievement Challenge Level #3',
    description: 'Complete match milestone challenge #3 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 15,
    rewardCoins: 600,
    rewardGems: 15,
    rewardXP: 150,
  },
  {
    id: 'ach_exp_4',
    title: 'Achievement Challenge Level #4',
    description: 'Complete match milestone challenge #4 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 20,
    rewardCoins: 800,
    rewardGems: 20,
    rewardXP: 200,
  },
  {
    id: 'ach_exp_5',
    title: 'Achievement Challenge Level #5',
    description: 'Complete match milestone challenge #5 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 25,
    rewardCoins: 1000,
    rewardGems: 25,
    rewardXP: 250,
  },
  {
    id: 'ach_exp_6',
    title: 'Achievement Challenge Level #6',
    description: 'Complete match milestone challenge #6 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 30,
    rewardCoins: 1200,
    rewardGems: 30,
    rewardXP: 300,
  },
  {
    id: 'ach_exp_7',
    title: 'Achievement Challenge Level #7',
    description: 'Complete match milestone challenge #7 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 35,
    rewardCoins: 1400,
    rewardGems: 35,
    rewardXP: 350,
  },
  {
    id: 'ach_exp_8',
    title: 'Achievement Challenge Level #8',
    description: 'Complete match milestone challenge #8 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 40,
    rewardCoins: 1600,
    rewardGems: 40,
    rewardXP: 400,
  },
  {
    id: 'ach_exp_9',
    title: 'Achievement Challenge Level #9',
    description: 'Complete match milestone challenge #9 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 45,
    rewardCoins: 1800,
    rewardGems: 45,
    rewardXP: 450,
  },
  {
    id: 'ach_exp_10',
    title: 'Achievement Challenge Level #10',
    description: 'Complete match milestone challenge #10 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 50,
    rewardCoins: 2000,
    rewardGems: 50,
    rewardXP: 500,
  },
  {
    id: 'ach_exp_11',
    title: 'Achievement Challenge Level #11',
    description: 'Complete match milestone challenge #11 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 55,
    rewardCoins: 2200,
    rewardGems: 55,
    rewardXP: 550,
  },
  {
    id: 'ach_exp_12',
    title: 'Achievement Challenge Level #12',
    description: 'Complete match milestone challenge #12 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 60,
    rewardCoins: 2400,
    rewardGems: 60,
    rewardXP: 600,
  },
  {
    id: 'ach_exp_13',
    title: 'Achievement Challenge Level #13',
    description: 'Complete match milestone challenge #13 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 65,
    rewardCoins: 2600,
    rewardGems: 65,
    rewardXP: 650,
  },
  {
    id: 'ach_exp_14',
    title: 'Achievement Challenge Level #14',
    description: 'Complete match milestone challenge #14 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 70,
    rewardCoins: 2800,
    rewardGems: 70,
    rewardXP: 700,
  },
  {
    id: 'ach_exp_15',
    title: 'Achievement Challenge Level #15',
    description: 'Complete match milestone challenge #15 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 75,
    rewardCoins: 3000,
    rewardGems: 75,
    rewardXP: 750,
  },
  {
    id: 'ach_exp_16',
    title: 'Achievement Challenge Level #16',
    description: 'Complete match milestone challenge #16 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 80,
    rewardCoins: 3200,
    rewardGems: 80,
    rewardXP: 800,
  },
  {
    id: 'ach_exp_17',
    title: 'Achievement Challenge Level #17',
    description: 'Complete match milestone challenge #17 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 85,
    rewardCoins: 3400,
    rewardGems: 85,
    rewardXP: 850,
  },
  {
    id: 'ach_exp_18',
    title: 'Achievement Challenge Level #18',
    description: 'Complete match milestone challenge #18 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 90,
    rewardCoins: 3600,
    rewardGems: 90,
    rewardXP: 900,
  },
  {
    id: 'ach_exp_19',
    title: 'Achievement Challenge Level #19',
    description: 'Complete match milestone challenge #19 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 95,
    rewardCoins: 3800,
    rewardGems: 95,
    rewardXP: 950,
  },
  {
    id: 'ach_exp_20',
    title: 'Achievement Challenge Level #20',
    description: 'Complete match milestone challenge #20 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 100,
    rewardCoins: 4000,
    rewardGems: 100,
    rewardXP: 1000,
  },
  {
    id: 'ach_exp_21',
    title: 'Achievement Challenge Level #21',
    description: 'Complete match milestone challenge #21 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 105,
    rewardCoins: 4200,
    rewardGems: 105,
    rewardXP: 1050,
  },
  {
    id: 'ach_exp_22',
    title: 'Achievement Challenge Level #22',
    description: 'Complete match milestone challenge #22 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 110,
    rewardCoins: 4400,
    rewardGems: 110,
    rewardXP: 1100,
  },
  {
    id: 'ach_exp_23',
    title: 'Achievement Challenge Level #23',
    description: 'Complete match milestone challenge #23 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 115,
    rewardCoins: 4600,
    rewardGems: 115,
    rewardXP: 1150,
  },
  {
    id: 'ach_exp_24',
    title: 'Achievement Challenge Level #24',
    description: 'Complete match milestone challenge #24 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 120,
    rewardCoins: 4800,
    rewardGems: 120,
    rewardXP: 1200,
  },
  {
    id: 'ach_exp_25',
    title: 'Achievement Challenge Level #25',
    description: 'Complete match milestone challenge #25 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 125,
    rewardCoins: 5000,
    rewardGems: 125,
    rewardXP: 1250,
  },
  {
    id: 'ach_exp_26',
    title: 'Achievement Challenge Level #26',
    description: 'Complete match milestone challenge #26 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 130,
    rewardCoins: 5200,
    rewardGems: 130,
    rewardXP: 1300,
  },
  {
    id: 'ach_exp_27',
    title: 'Achievement Challenge Level #27',
    description: 'Complete match milestone challenge #27 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 135,
    rewardCoins: 5400,
    rewardGems: 135,
    rewardXP: 1350,
  },
  {
    id: 'ach_exp_28',
    title: 'Achievement Challenge Level #28',
    description: 'Complete match milestone challenge #28 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 140,
    rewardCoins: 5600,
    rewardGems: 140,
    rewardXP: 1400,
  },
  {
    id: 'ach_exp_29',
    title: 'Achievement Challenge Level #29',
    description: 'Complete match milestone challenge #29 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 145,
    rewardCoins: 5800,
    rewardGems: 145,
    rewardXP: 1450,
  },
  {
    id: 'ach_exp_30',
    title: 'Achievement Challenge Level #30',
    description: 'Complete match milestone challenge #30 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 150,
    rewardCoins: 6000,
    rewardGems: 150,
    rewardXP: 1500,
  },
  {
    id: 'ach_exp_31',
    title: 'Achievement Challenge Level #31',
    description: 'Complete match milestone challenge #31 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 155,
    rewardCoins: 6200,
    rewardGems: 155,
    rewardXP: 1550,
  },
  {
    id: 'ach_exp_32',
    title: 'Achievement Challenge Level #32',
    description: 'Complete match milestone challenge #32 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 160,
    rewardCoins: 6400,
    rewardGems: 160,
    rewardXP: 1600,
  },
  {
    id: 'ach_exp_33',
    title: 'Achievement Challenge Level #33',
    description: 'Complete match milestone challenge #33 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 165,
    rewardCoins: 6600,
    rewardGems: 165,
    rewardXP: 1650,
  },
  {
    id: 'ach_exp_34',
    title: 'Achievement Challenge Level #34',
    description: 'Complete match milestone challenge #34 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 170,
    rewardCoins: 6800,
    rewardGems: 170,
    rewardXP: 1700,
  },
  {
    id: 'ach_exp_35',
    title: 'Achievement Challenge Level #35',
    description: 'Complete match milestone challenge #35 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 175,
    rewardCoins: 7000,
    rewardGems: 175,
    rewardXP: 1750,
  },
  {
    id: 'ach_exp_36',
    title: 'Achievement Challenge Level #36',
    description: 'Complete match milestone challenge #36 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 180,
    rewardCoins: 7200,
    rewardGems: 180,
    rewardXP: 1800,
  },
  {
    id: 'ach_exp_37',
    title: 'Achievement Challenge Level #37',
    description: 'Complete match milestone challenge #37 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 185,
    rewardCoins: 7400,
    rewardGems: 185,
    rewardXP: 1850,
  },
  {
    id: 'ach_exp_38',
    title: 'Achievement Challenge Level #38',
    description: 'Complete match milestone challenge #38 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 190,
    rewardCoins: 7600,
    rewardGems: 190,
    rewardXP: 1900,
  },
  {
    id: 'ach_exp_39',
    title: 'Achievement Challenge Level #39',
    description: 'Complete match milestone challenge #39 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 195,
    rewardCoins: 7800,
    rewardGems: 195,
    rewardXP: 1950,
  },
  {
    id: 'ach_exp_40',
    title: 'Achievement Challenge Level #40',
    description: 'Complete match milestone challenge #40 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 200,
    rewardCoins: 8000,
    rewardGems: 200,
    rewardXP: 2000,
  },
  {
    id: 'ach_exp_41',
    title: 'Achievement Challenge Level #41',
    description: 'Complete match milestone challenge #41 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 205,
    rewardCoins: 8200,
    rewardGems: 205,
    rewardXP: 2050,
  },
  {
    id: 'ach_exp_42',
    title: 'Achievement Challenge Level #42',
    description: 'Complete match milestone challenge #42 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 210,
    rewardCoins: 8400,
    rewardGems: 210,
    rewardXP: 2100,
  },
  {
    id: 'ach_exp_43',
    title: 'Achievement Challenge Level #43',
    description: 'Complete match milestone challenge #43 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 215,
    rewardCoins: 8600,
    rewardGems: 215,
    rewardXP: 2150,
  },
  {
    id: 'ach_exp_44',
    title: 'Achievement Challenge Level #44',
    description: 'Complete match milestone challenge #44 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 220,
    rewardCoins: 8800,
    rewardGems: 220,
    rewardXP: 2200,
  },
  {
    id: 'ach_exp_45',
    title: 'Achievement Challenge Level #45',
    description: 'Complete match milestone challenge #45 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 225,
    rewardCoins: 9000,
    rewardGems: 225,
    rewardXP: 2250,
  },
  {
    id: 'ach_exp_46',
    title: 'Achievement Challenge Level #46',
    description: 'Complete match milestone challenge #46 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 230,
    rewardCoins: 9200,
    rewardGems: 230,
    rewardXP: 2300,
  },
  {
    id: 'ach_exp_47',
    title: 'Achievement Challenge Level #47',
    description: 'Complete match milestone challenge #47 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 235,
    rewardCoins: 9400,
    rewardGems: 235,
    rewardXP: 2350,
  },
  {
    id: 'ach_exp_48',
    title: 'Achievement Challenge Level #48',
    description: 'Complete match milestone challenge #48 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 240,
    rewardCoins: 9600,
    rewardGems: 240,
    rewardXP: 2400,
  },
  {
    id: 'ach_exp_49',
    title: 'Achievement Challenge Level #49',
    description: 'Complete match milestone challenge #49 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 245,
    rewardCoins: 9800,
    rewardGems: 245,
    rewardXP: 2450,
  },
  {
    id: 'ach_exp_50',
    title: 'Achievement Challenge Level #50',
    description: 'Complete match milestone challenge #50 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 250,
    rewardCoins: 10000,
    rewardGems: 250,
    rewardXP: 2500,
  },
  {
    id: 'ach_exp_51',
    title: 'Achievement Challenge Level #51',
    description: 'Complete match milestone challenge #51 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 255,
    rewardCoins: 10200,
    rewardGems: 255,
    rewardXP: 2550,
  },
  {
    id: 'ach_exp_52',
    title: 'Achievement Challenge Level #52',
    description: 'Complete match milestone challenge #52 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 260,
    rewardCoins: 10400,
    rewardGems: 260,
    rewardXP: 2600,
  },
  {
    id: 'ach_exp_53',
    title: 'Achievement Challenge Level #53',
    description: 'Complete match milestone challenge #53 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 265,
    rewardCoins: 10600,
    rewardGems: 265,
    rewardXP: 2650,
  },
  {
    id: 'ach_exp_54',
    title: 'Achievement Challenge Level #54',
    description: 'Complete match milestone challenge #54 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 270,
    rewardCoins: 10800,
    rewardGems: 270,
    rewardXP: 2700,
  },
  {
    id: 'ach_exp_55',
    title: 'Achievement Challenge Level #55',
    description: 'Complete match milestone challenge #55 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 275,
    rewardCoins: 11000,
    rewardGems: 275,
    rewardXP: 2750,
  },
  {
    id: 'ach_exp_56',
    title: 'Achievement Challenge Level #56',
    description: 'Complete match milestone challenge #56 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 280,
    rewardCoins: 11200,
    rewardGems: 280,
    rewardXP: 2800,
  },
  {
    id: 'ach_exp_57',
    title: 'Achievement Challenge Level #57',
    description: 'Complete match milestone challenge #57 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 285,
    rewardCoins: 11400,
    rewardGems: 285,
    rewardXP: 2850,
  },
  {
    id: 'ach_exp_58',
    title: 'Achievement Challenge Level #58',
    description: 'Complete match milestone challenge #58 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 290,
    rewardCoins: 11600,
    rewardGems: 290,
    rewardXP: 2900,
  },
  {
    id: 'ach_exp_59',
    title: 'Achievement Challenge Level #59',
    description: 'Complete match milestone challenge #59 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 295,
    rewardCoins: 11800,
    rewardGems: 295,
    rewardXP: 2950,
  },
  {
    id: 'ach_exp_60',
    title: 'Achievement Challenge Level #60',
    description: 'Complete match milestone challenge #60 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 300,
    rewardCoins: 12000,
    rewardGems: 300,
    rewardXP: 3000,
  },
  {
    id: 'ach_exp_61',
    title: 'Achievement Challenge Level #61',
    description: 'Complete match milestone challenge #61 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 305,
    rewardCoins: 12200,
    rewardGems: 305,
    rewardXP: 3050,
  },
  {
    id: 'ach_exp_62',
    title: 'Achievement Challenge Level #62',
    description: 'Complete match milestone challenge #62 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 310,
    rewardCoins: 12400,
    rewardGems: 310,
    rewardXP: 3100,
  },
  {
    id: 'ach_exp_63',
    title: 'Achievement Challenge Level #63',
    description: 'Complete match milestone challenge #63 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 315,
    rewardCoins: 12600,
    rewardGems: 315,
    rewardXP: 3150,
  },
  {
    id: 'ach_exp_64',
    title: 'Achievement Challenge Level #64',
    description: 'Complete match milestone challenge #64 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 320,
    rewardCoins: 12800,
    rewardGems: 320,
    rewardXP: 3200,
  },
  {
    id: 'ach_exp_65',
    title: 'Achievement Challenge Level #65',
    description: 'Complete match milestone challenge #65 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 325,
    rewardCoins: 13000,
    rewardGems: 325,
    rewardXP: 3250,
  },
  {
    id: 'ach_exp_66',
    title: 'Achievement Challenge Level #66',
    description: 'Complete match milestone challenge #66 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 330,
    rewardCoins: 13200,
    rewardGems: 330,
    rewardXP: 3300,
  },
  {
    id: 'ach_exp_67',
    title: 'Achievement Challenge Level #67',
    description: 'Complete match milestone challenge #67 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 335,
    rewardCoins: 13400,
    rewardGems: 335,
    rewardXP: 3350,
  },
  {
    id: 'ach_exp_68',
    title: 'Achievement Challenge Level #68',
    description: 'Complete match milestone challenge #68 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 340,
    rewardCoins: 13600,
    rewardGems: 340,
    rewardXP: 3400,
  },
  {
    id: 'ach_exp_69',
    title: 'Achievement Challenge Level #69',
    description: 'Complete match milestone challenge #69 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 345,
    rewardCoins: 13800,
    rewardGems: 345,
    rewardXP: 3450,
  },
  {
    id: 'ach_exp_70',
    title: 'Achievement Challenge Level #70',
    description: 'Complete match milestone challenge #70 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 350,
    rewardCoins: 14000,
    rewardGems: 350,
    rewardXP: 3500,
  },
  {
    id: 'ach_exp_71',
    title: 'Achievement Challenge Level #71',
    description: 'Complete match milestone challenge #71 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 355,
    rewardCoins: 14200,
    rewardGems: 355,
    rewardXP: 3550,
  },
  {
    id: 'ach_exp_72',
    title: 'Achievement Challenge Level #72',
    description: 'Complete match milestone challenge #72 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 360,
    rewardCoins: 14400,
    rewardGems: 360,
    rewardXP: 3600,
  },
  {
    id: 'ach_exp_73',
    title: 'Achievement Challenge Level #73',
    description: 'Complete match milestone challenge #73 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 365,
    rewardCoins: 14600,
    rewardGems: 365,
    rewardXP: 3650,
  },
  {
    id: 'ach_exp_74',
    title: 'Achievement Challenge Level #74',
    description: 'Complete match milestone challenge #74 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 370,
    rewardCoins: 14800,
    rewardGems: 370,
    rewardXP: 3700,
  },
  {
    id: 'ach_exp_75',
    title: 'Achievement Challenge Level #75',
    description: 'Complete match milestone challenge #75 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 375,
    rewardCoins: 15000,
    rewardGems: 375,
    rewardXP: 3750,
  },
  {
    id: 'ach_exp_76',
    title: 'Achievement Challenge Level #76',
    description: 'Complete match milestone challenge #76 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 380,
    rewardCoins: 15200,
    rewardGems: 380,
    rewardXP: 3800,
  },
  {
    id: 'ach_exp_77',
    title: 'Achievement Challenge Level #77',
    description: 'Complete match milestone challenge #77 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 385,
    rewardCoins: 15400,
    rewardGems: 385,
    rewardXP: 3850,
  },
  {
    id: 'ach_exp_78',
    title: 'Achievement Challenge Level #78',
    description: 'Complete match milestone challenge #78 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 390,
    rewardCoins: 15600,
    rewardGems: 390,
    rewardXP: 3900,
  },
  {
    id: 'ach_exp_79',
    title: 'Achievement Challenge Level #79',
    description: 'Complete match milestone challenge #79 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 395,
    rewardCoins: 15800,
    rewardGems: 395,
    rewardXP: 3950,
  },
  {
    id: 'ach_exp_80',
    title: 'Achievement Challenge Level #80',
    description: 'Complete match milestone challenge #80 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 400,
    rewardCoins: 16000,
    rewardGems: 400,
    rewardXP: 4000,
  },
  {
    id: 'ach_exp_81',
    title: 'Achievement Challenge Level #81',
    description: 'Complete match milestone challenge #81 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 405,
    rewardCoins: 16200,
    rewardGems: 405,
    rewardXP: 4050,
  },
  {
    id: 'ach_exp_82',
    title: 'Achievement Challenge Level #82',
    description: 'Complete match milestone challenge #82 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 410,
    rewardCoins: 16400,
    rewardGems: 410,
    rewardXP: 4100,
  },
  {
    id: 'ach_exp_83',
    title: 'Achievement Challenge Level #83',
    description: 'Complete match milestone challenge #83 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 415,
    rewardCoins: 16600,
    rewardGems: 415,
    rewardXP: 4150,
  },
  {
    id: 'ach_exp_84',
    title: 'Achievement Challenge Level #84',
    description: 'Complete match milestone challenge #84 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 420,
    rewardCoins: 16800,
    rewardGems: 420,
    rewardXP: 4200,
  },
  {
    id: 'ach_exp_85',
    title: 'Achievement Challenge Level #85',
    description: 'Complete match milestone challenge #85 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 425,
    rewardCoins: 17000,
    rewardGems: 425,
    rewardXP: 4250,
  },
  {
    id: 'ach_exp_86',
    title: 'Achievement Challenge Level #86',
    description: 'Complete match milestone challenge #86 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 430,
    rewardCoins: 17200,
    rewardGems: 430,
    rewardXP: 4300,
  },
  {
    id: 'ach_exp_87',
    title: 'Achievement Challenge Level #87',
    description: 'Complete match milestone challenge #87 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 435,
    rewardCoins: 17400,
    rewardGems: 435,
    rewardXP: 4350,
  },
  {
    id: 'ach_exp_88',
    title: 'Achievement Challenge Level #88',
    description: 'Complete match milestone challenge #88 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 440,
    rewardCoins: 17600,
    rewardGems: 440,
    rewardXP: 4400,
  },
  {
    id: 'ach_exp_89',
    title: 'Achievement Challenge Level #89',
    description: 'Complete match milestone challenge #89 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 445,
    rewardCoins: 17800,
    rewardGems: 445,
    rewardXP: 4450,
  },
  {
    id: 'ach_exp_90',
    title: 'Achievement Challenge Level #90',
    description: 'Complete match milestone challenge #90 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 450,
    rewardCoins: 18000,
    rewardGems: 450,
    rewardXP: 4500,
  },
  {
    id: 'ach_exp_91',
    title: 'Achievement Challenge Level #91',
    description: 'Complete match milestone challenge #91 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 455,
    rewardCoins: 18200,
    rewardGems: 455,
    rewardXP: 4550,
  },
  {
    id: 'ach_exp_92',
    title: 'Achievement Challenge Level #92',
    description: 'Complete match milestone challenge #92 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 460,
    rewardCoins: 18400,
    rewardGems: 460,
    rewardXP: 4600,
  },
  {
    id: 'ach_exp_93',
    title: 'Achievement Challenge Level #93',
    description: 'Complete match milestone challenge #93 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 465,
    rewardCoins: 18600,
    rewardGems: 465,
    rewardXP: 4650,
  },
  {
    id: 'ach_exp_94',
    title: 'Achievement Challenge Level #94',
    description: 'Complete match milestone challenge #94 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 470,
    rewardCoins: 18800,
    rewardGems: 470,
    rewardXP: 4700,
  },
  {
    id: 'ach_exp_95',
    title: 'Achievement Challenge Level #95',
    description: 'Complete match milestone challenge #95 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 475,
    rewardCoins: 19000,
    rewardGems: 475,
    rewardXP: 4750,
  },
  {
    id: 'ach_exp_96',
    title: 'Achievement Challenge Level #96',
    description: 'Complete match milestone challenge #96 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 480,
    rewardCoins: 19200,
    rewardGems: 480,
    rewardXP: 4800,
  },
  {
    id: 'ach_exp_97',
    title: 'Achievement Challenge Level #97',
    description: 'Complete match milestone challenge #97 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 485,
    rewardCoins: 19400,
    rewardGems: 485,
    rewardXP: 4850,
  },
  {
    id: 'ach_exp_98',
    title: 'Achievement Challenge Level #98',
    description: 'Complete match milestone challenge #98 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 490,
    rewardCoins: 19600,
    rewardGems: 490,
    rewardXP: 4900,
  },
  {
    id: 'ach_exp_99',
    title: 'Achievement Challenge Level #99',
    description: 'Complete match milestone challenge #99 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 495,
    rewardCoins: 19800,
    rewardGems: 495,
    rewardXP: 4950,
  },
  {
    id: 'ach_exp_100',
    title: 'Achievement Challenge Level #100',
    description: 'Complete match milestone challenge #100 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 500,
    rewardCoins: 20000,
    rewardGems: 500,
    rewardXP: 5000,
  },
  {
    id: 'ach_exp_101',
    title: 'Achievement Challenge Level #101',
    description: 'Complete match milestone challenge #101 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 505,
    rewardCoins: 20200,
    rewardGems: 505,
    rewardXP: 5050,
  },
  {
    id: 'ach_exp_102',
    title: 'Achievement Challenge Level #102',
    description: 'Complete match milestone challenge #102 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 510,
    rewardCoins: 20400,
    rewardGems: 510,
    rewardXP: 5100,
  },
  {
    id: 'ach_exp_103',
    title: 'Achievement Challenge Level #103',
    description: 'Complete match milestone challenge #103 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 515,
    rewardCoins: 20600,
    rewardGems: 515,
    rewardXP: 5150,
  },
  {
    id: 'ach_exp_104',
    title: 'Achievement Challenge Level #104',
    description: 'Complete match milestone challenge #104 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 520,
    rewardCoins: 20800,
    rewardGems: 520,
    rewardXP: 5200,
  },
  {
    id: 'ach_exp_105',
    title: 'Achievement Challenge Level #105',
    description: 'Complete match milestone challenge #105 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 525,
    rewardCoins: 21000,
    rewardGems: 525,
    rewardXP: 5250,
  },
  {
    id: 'ach_exp_106',
    title: 'Achievement Challenge Level #106',
    description: 'Complete match milestone challenge #106 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 530,
    rewardCoins: 21200,
    rewardGems: 530,
    rewardXP: 5300,
  },
  {
    id: 'ach_exp_107',
    title: 'Achievement Challenge Level #107',
    description: 'Complete match milestone challenge #107 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 535,
    rewardCoins: 21400,
    rewardGems: 535,
    rewardXP: 5350,
  },
  {
    id: 'ach_exp_108',
    title: 'Achievement Challenge Level #108',
    description: 'Complete match milestone challenge #108 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 540,
    rewardCoins: 21600,
    rewardGems: 540,
    rewardXP: 5400,
  },
  {
    id: 'ach_exp_109',
    title: 'Achievement Challenge Level #109',
    description: 'Complete match milestone challenge #109 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 545,
    rewardCoins: 21800,
    rewardGems: 545,
    rewardXP: 5450,
  },
  {
    id: 'ach_exp_110',
    title: 'Achievement Challenge Level #110',
    description: 'Complete match milestone challenge #110 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 550,
    rewardCoins: 22000,
    rewardGems: 550,
    rewardXP: 5500,
  },
  {
    id: 'ach_exp_111',
    title: 'Achievement Challenge Level #111',
    description: 'Complete match milestone challenge #111 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 555,
    rewardCoins: 22200,
    rewardGems: 555,
    rewardXP: 5550,
  },
  {
    id: 'ach_exp_112',
    title: 'Achievement Challenge Level #112',
    description: 'Complete match milestone challenge #112 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 560,
    rewardCoins: 22400,
    rewardGems: 560,
    rewardXP: 5600,
  },
  {
    id: 'ach_exp_113',
    title: 'Achievement Challenge Level #113',
    description: 'Complete match milestone challenge #113 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 565,
    rewardCoins: 22600,
    rewardGems: 565,
    rewardXP: 5650,
  },
  {
    id: 'ach_exp_114',
    title: 'Achievement Challenge Level #114',
    description: 'Complete match milestone challenge #114 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 570,
    rewardCoins: 22800,
    rewardGems: 570,
    rewardXP: 5700,
  },
  {
    id: 'ach_exp_115',
    title: 'Achievement Challenge Level #115',
    description: 'Complete match milestone challenge #115 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 575,
    rewardCoins: 23000,
    rewardGems: 575,
    rewardXP: 5750,
  },
  {
    id: 'ach_exp_116',
    title: 'Achievement Challenge Level #116',
    description: 'Complete match milestone challenge #116 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 580,
    rewardCoins: 23200,
    rewardGems: 580,
    rewardXP: 5800,
  },
  {
    id: 'ach_exp_117',
    title: 'Achievement Challenge Level #117',
    description: 'Complete match milestone challenge #117 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 585,
    rewardCoins: 23400,
    rewardGems: 585,
    rewardXP: 5850,
  },
  {
    id: 'ach_exp_118',
    title: 'Achievement Challenge Level #118',
    description: 'Complete match milestone challenge #118 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 590,
    rewardCoins: 23600,
    rewardGems: 590,
    rewardXP: 5900,
  },
  {
    id: 'ach_exp_119',
    title: 'Achievement Challenge Level #119',
    description: 'Complete match milestone challenge #119 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 595,
    rewardCoins: 23800,
    rewardGems: 595,
    rewardXP: 5950,
  },
  {
    id: 'ach_exp_120',
    title: 'Achievement Challenge Level #120',
    description: 'Complete match milestone challenge #120 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 600,
    rewardCoins: 24000,
    rewardGems: 600,
    rewardXP: 6000,
  },
  {
    id: 'ach_exp_121',
    title: 'Achievement Challenge Level #121',
    description: 'Complete match milestone challenge #121 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 605,
    rewardCoins: 24200,
    rewardGems: 605,
    rewardXP: 6050,
  },
  {
    id: 'ach_exp_122',
    title: 'Achievement Challenge Level #122',
    description: 'Complete match milestone challenge #122 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 610,
    rewardCoins: 24400,
    rewardGems: 610,
    rewardXP: 6100,
  },
  {
    id: 'ach_exp_123',
    title: 'Achievement Challenge Level #123',
    description: 'Complete match milestone challenge #123 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 615,
    rewardCoins: 24600,
    rewardGems: 615,
    rewardXP: 6150,
  },
  {
    id: 'ach_exp_124',
    title: 'Achievement Challenge Level #124',
    description: 'Complete match milestone challenge #124 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 620,
    rewardCoins: 24800,
    rewardGems: 620,
    rewardXP: 6200,
  },
  {
    id: 'ach_exp_125',
    title: 'Achievement Challenge Level #125',
    description: 'Complete match milestone challenge #125 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 625,
    rewardCoins: 25000,
    rewardGems: 625,
    rewardXP: 6250,
  },
  {
    id: 'ach_exp_126',
    title: 'Achievement Challenge Level #126',
    description: 'Complete match milestone challenge #126 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 630,
    rewardCoins: 25200,
    rewardGems: 630,
    rewardXP: 6300,
  },
  {
    id: 'ach_exp_127',
    title: 'Achievement Challenge Level #127',
    description: 'Complete match milestone challenge #127 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 635,
    rewardCoins: 25400,
    rewardGems: 635,
    rewardXP: 6350,
  },
  {
    id: 'ach_exp_128',
    title: 'Achievement Challenge Level #128',
    description: 'Complete match milestone challenge #128 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 640,
    rewardCoins: 25600,
    rewardGems: 640,
    rewardXP: 6400,
  },
  {
    id: 'ach_exp_129',
    title: 'Achievement Challenge Level #129',
    description: 'Complete match milestone challenge #129 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 645,
    rewardCoins: 25800,
    rewardGems: 645,
    rewardXP: 6450,
  },
  {
    id: 'ach_exp_130',
    title: 'Achievement Challenge Level #130',
    description: 'Complete match milestone challenge #130 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 650,
    rewardCoins: 26000,
    rewardGems: 650,
    rewardXP: 6500,
  },
  {
    id: 'ach_exp_131',
    title: 'Achievement Challenge Level #131',
    description: 'Complete match milestone challenge #131 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 655,
    rewardCoins: 26200,
    rewardGems: 655,
    rewardXP: 6550,
  },
  {
    id: 'ach_exp_132',
    title: 'Achievement Challenge Level #132',
    description: 'Complete match milestone challenge #132 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 660,
    rewardCoins: 26400,
    rewardGems: 660,
    rewardXP: 6600,
  },
  {
    id: 'ach_exp_133',
    title: 'Achievement Challenge Level #133',
    description: 'Complete match milestone challenge #133 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 665,
    rewardCoins: 26600,
    rewardGems: 665,
    rewardXP: 6650,
  },
  {
    id: 'ach_exp_134',
    title: 'Achievement Challenge Level #134',
    description: 'Complete match milestone challenge #134 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 670,
    rewardCoins: 26800,
    rewardGems: 670,
    rewardXP: 6700,
  },
  {
    id: 'ach_exp_135',
    title: 'Achievement Challenge Level #135',
    description: 'Complete match milestone challenge #135 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 675,
    rewardCoins: 27000,
    rewardGems: 675,
    rewardXP: 6750,
  },
  {
    id: 'ach_exp_136',
    title: 'Achievement Challenge Level #136',
    description: 'Complete match milestone challenge #136 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 680,
    rewardCoins: 27200,
    rewardGems: 680,
    rewardXP: 6800,
  },
  {
    id: 'ach_exp_137',
    title: 'Achievement Challenge Level #137',
    description: 'Complete match milestone challenge #137 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 685,
    rewardCoins: 27400,
    rewardGems: 685,
    rewardXP: 6850,
  },
  {
    id: 'ach_exp_138',
    title: 'Achievement Challenge Level #138',
    description: 'Complete match milestone challenge #138 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 690,
    rewardCoins: 27600,
    rewardGems: 690,
    rewardXP: 6900,
  },
  {
    id: 'ach_exp_139',
    title: 'Achievement Challenge Level #139',
    description: 'Complete match milestone challenge #139 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 695,
    rewardCoins: 27800,
    rewardGems: 695,
    rewardXP: 6950,
  },
  {
    id: 'ach_exp_140',
    title: 'Achievement Challenge Level #140',
    description: 'Complete match milestone challenge #140 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 700,
    rewardCoins: 28000,
    rewardGems: 700,
    rewardXP: 7000,
  },
  {
    id: 'ach_exp_141',
    title: 'Achievement Challenge Level #141',
    description: 'Complete match milestone challenge #141 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 705,
    rewardCoins: 28200,
    rewardGems: 705,
    rewardXP: 7050,
  },
  {
    id: 'ach_exp_142',
    title: 'Achievement Challenge Level #142',
    description: 'Complete match milestone challenge #142 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 710,
    rewardCoins: 28400,
    rewardGems: 710,
    rewardXP: 7100,
  },
  {
    id: 'ach_exp_143',
    title: 'Achievement Challenge Level #143',
    description: 'Complete match milestone challenge #143 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 715,
    rewardCoins: 28600,
    rewardGems: 715,
    rewardXP: 7150,
  },
  {
    id: 'ach_exp_144',
    title: 'Achievement Challenge Level #144',
    description: 'Complete match milestone challenge #144 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 720,
    rewardCoins: 28800,
    rewardGems: 720,
    rewardXP: 7200,
  },
  {
    id: 'ach_exp_145',
    title: 'Achievement Challenge Level #145',
    description: 'Complete match milestone challenge #145 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 725,
    rewardCoins: 29000,
    rewardGems: 725,
    rewardXP: 7250,
  },
  {
    id: 'ach_exp_146',
    title: 'Achievement Challenge Level #146',
    description: 'Complete match milestone challenge #146 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 730,
    rewardCoins: 29200,
    rewardGems: 730,
    rewardXP: 7300,
  },
  {
    id: 'ach_exp_147',
    title: 'Achievement Challenge Level #147',
    description: 'Complete match milestone challenge #147 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 735,
    rewardCoins: 29400,
    rewardGems: 735,
    rewardXP: 7350,
  },
  {
    id: 'ach_exp_148',
    title: 'Achievement Challenge Level #148',
    description: 'Complete match milestone challenge #148 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 740,
    rewardCoins: 29600,
    rewardGems: 740,
    rewardXP: 7400,
  },
  {
    id: 'ach_exp_149',
    title: 'Achievement Challenge Level #149',
    description: 'Complete match milestone challenge #149 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 745,
    rewardCoins: 29800,
    rewardGems: 745,
    rewardXP: 7450,
  },
  {
    id: 'ach_exp_150',
    title: 'Achievement Challenge Level #150',
    description: 'Complete match milestone challenge #150 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 750,
    rewardCoins: 30000,
    rewardGems: 750,
    rewardXP: 7500,
  },
  {
    id: 'ach_exp_151',
    title: 'Achievement Challenge Level #151',
    description: 'Complete match milestone challenge #151 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 755,
    rewardCoins: 30200,
    rewardGems: 755,
    rewardXP: 7550,
  },
  {
    id: 'ach_exp_152',
    title: 'Achievement Challenge Level #152',
    description: 'Complete match milestone challenge #152 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 760,
    rewardCoins: 30400,
    rewardGems: 760,
    rewardXP: 7600,
  },
  {
    id: 'ach_exp_153',
    title: 'Achievement Challenge Level #153',
    description: 'Complete match milestone challenge #153 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 765,
    rewardCoins: 30600,
    rewardGems: 765,
    rewardXP: 7650,
  },
  {
    id: 'ach_exp_154',
    title: 'Achievement Challenge Level #154',
    description: 'Complete match milestone challenge #154 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 770,
    rewardCoins: 30800,
    rewardGems: 770,
    rewardXP: 7700,
  },
  {
    id: 'ach_exp_155',
    title: 'Achievement Challenge Level #155',
    description: 'Complete match milestone challenge #155 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 775,
    rewardCoins: 31000,
    rewardGems: 775,
    rewardXP: 7750,
  },
  {
    id: 'ach_exp_156',
    title: 'Achievement Challenge Level #156',
    description: 'Complete match milestone challenge #156 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 780,
    rewardCoins: 31200,
    rewardGems: 780,
    rewardXP: 7800,
  },
  {
    id: 'ach_exp_157',
    title: 'Achievement Challenge Level #157',
    description: 'Complete match milestone challenge #157 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 785,
    rewardCoins: 31400,
    rewardGems: 785,
    rewardXP: 7850,
  },
  {
    id: 'ach_exp_158',
    title: 'Achievement Challenge Level #158',
    description: 'Complete match milestone challenge #158 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 790,
    rewardCoins: 31600,
    rewardGems: 790,
    rewardXP: 7900,
  },
  {
    id: 'ach_exp_159',
    title: 'Achievement Challenge Level #159',
    description: 'Complete match milestone challenge #159 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 795,
    rewardCoins: 31800,
    rewardGems: 795,
    rewardXP: 7950,
  },
  {
    id: 'ach_exp_160',
    title: 'Achievement Challenge Level #160',
    description: 'Complete match milestone challenge #160 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 800,
    rewardCoins: 32000,
    rewardGems: 800,
    rewardXP: 8000,
  },
  {
    id: 'ach_exp_161',
    title: 'Achievement Challenge Level #161',
    description: 'Complete match milestone challenge #161 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 805,
    rewardCoins: 32200,
    rewardGems: 805,
    rewardXP: 8050,
  },
  {
    id: 'ach_exp_162',
    title: 'Achievement Challenge Level #162',
    description: 'Complete match milestone challenge #162 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 810,
    rewardCoins: 32400,
    rewardGems: 810,
    rewardXP: 8100,
  },
  {
    id: 'ach_exp_163',
    title: 'Achievement Challenge Level #163',
    description: 'Complete match milestone challenge #163 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 815,
    rewardCoins: 32600,
    rewardGems: 815,
    rewardXP: 8150,
  },
  {
    id: 'ach_exp_164',
    title: 'Achievement Challenge Level #164',
    description: 'Complete match milestone challenge #164 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 820,
    rewardCoins: 32800,
    rewardGems: 820,
    rewardXP: 8200,
  },
  {
    id: 'ach_exp_165',
    title: 'Achievement Challenge Level #165',
    description: 'Complete match milestone challenge #165 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 825,
    rewardCoins: 33000,
    rewardGems: 825,
    rewardXP: 8250,
  },
  {
    id: 'ach_exp_166',
    title: 'Achievement Challenge Level #166',
    description: 'Complete match milestone challenge #166 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 830,
    rewardCoins: 33200,
    rewardGems: 830,
    rewardXP: 8300,
  },
  {
    id: 'ach_exp_167',
    title: 'Achievement Challenge Level #167',
    description: 'Complete match milestone challenge #167 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 835,
    rewardCoins: 33400,
    rewardGems: 835,
    rewardXP: 8350,
  },
  {
    id: 'ach_exp_168',
    title: 'Achievement Challenge Level #168',
    description: 'Complete match milestone challenge #168 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 840,
    rewardCoins: 33600,
    rewardGems: 840,
    rewardXP: 8400,
  },
  {
    id: 'ach_exp_169',
    title: 'Achievement Challenge Level #169',
    description: 'Complete match milestone challenge #169 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 845,
    rewardCoins: 33800,
    rewardGems: 845,
    rewardXP: 8450,
  },
  {
    id: 'ach_exp_170',
    title: 'Achievement Challenge Level #170',
    description: 'Complete match milestone challenge #170 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 850,
    rewardCoins: 34000,
    rewardGems: 850,
    rewardXP: 8500,
  },
  {
    id: 'ach_exp_171',
    title: 'Achievement Challenge Level #171',
    description: 'Complete match milestone challenge #171 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 855,
    rewardCoins: 34200,
    rewardGems: 855,
    rewardXP: 8550,
  },
  {
    id: 'ach_exp_172',
    title: 'Achievement Challenge Level #172',
    description: 'Complete match milestone challenge #172 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 860,
    rewardCoins: 34400,
    rewardGems: 860,
    rewardXP: 8600,
  },
  {
    id: 'ach_exp_173',
    title: 'Achievement Challenge Level #173',
    description: 'Complete match milestone challenge #173 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 865,
    rewardCoins: 34600,
    rewardGems: 865,
    rewardXP: 8650,
  },
  {
    id: 'ach_exp_174',
    title: 'Achievement Challenge Level #174',
    description: 'Complete match milestone challenge #174 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 870,
    rewardCoins: 34800,
    rewardGems: 870,
    rewardXP: 8700,
  },
  {
    id: 'ach_exp_175',
    title: 'Achievement Challenge Level #175',
    description: 'Complete match milestone challenge #175 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 875,
    rewardCoins: 35000,
    rewardGems: 875,
    rewardXP: 8750,
  },
  {
    id: 'ach_exp_176',
    title: 'Achievement Challenge Level #176',
    description: 'Complete match milestone challenge #176 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 880,
    rewardCoins: 35200,
    rewardGems: 880,
    rewardXP: 8800,
  },
  {
    id: 'ach_exp_177',
    title: 'Achievement Challenge Level #177',
    description: 'Complete match milestone challenge #177 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 885,
    rewardCoins: 35400,
    rewardGems: 885,
    rewardXP: 8850,
  },
  {
    id: 'ach_exp_178',
    title: 'Achievement Challenge Level #178',
    description: 'Complete match milestone challenge #178 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 890,
    rewardCoins: 35600,
    rewardGems: 890,
    rewardXP: 8900,
  },
  {
    id: 'ach_exp_179',
    title: 'Achievement Challenge Level #179',
    description: 'Complete match milestone challenge #179 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 895,
    rewardCoins: 35800,
    rewardGems: 895,
    rewardXP: 8950,
  },
  {
    id: 'ach_exp_180',
    title: 'Achievement Challenge Level #180',
    description: 'Complete match milestone challenge #180 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 900,
    rewardCoins: 36000,
    rewardGems: 900,
    rewardXP: 9000,
  },
  {
    id: 'ach_exp_181',
    title: 'Achievement Challenge Level #181',
    description: 'Complete match milestone challenge #181 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 905,
    rewardCoins: 36200,
    rewardGems: 905,
    rewardXP: 9050,
  },
  {
    id: 'ach_exp_182',
    title: 'Achievement Challenge Level #182',
    description: 'Complete match milestone challenge #182 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 910,
    rewardCoins: 36400,
    rewardGems: 910,
    rewardXP: 9100,
  },
  {
    id: 'ach_exp_183',
    title: 'Achievement Challenge Level #183',
    description: 'Complete match milestone challenge #183 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 915,
    rewardCoins: 36600,
    rewardGems: 915,
    rewardXP: 9150,
  },
  {
    id: 'ach_exp_184',
    title: 'Achievement Challenge Level #184',
    description: 'Complete match milestone challenge #184 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 920,
    rewardCoins: 36800,
    rewardGems: 920,
    rewardXP: 9200,
  },
  {
    id: 'ach_exp_185',
    title: 'Achievement Challenge Level #185',
    description: 'Complete match milestone challenge #185 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 925,
    rewardCoins: 37000,
    rewardGems: 925,
    rewardXP: 9250,
  },
  {
    id: 'ach_exp_186',
    title: 'Achievement Challenge Level #186',
    description: 'Complete match milestone challenge #186 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 930,
    rewardCoins: 37200,
    rewardGems: 930,
    rewardXP: 9300,
  },
  {
    id: 'ach_exp_187',
    title: 'Achievement Challenge Level #187',
    description: 'Complete match milestone challenge #187 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 935,
    rewardCoins: 37400,
    rewardGems: 935,
    rewardXP: 9350,
  },
  {
    id: 'ach_exp_188',
    title: 'Achievement Challenge Level #188',
    description: 'Complete match milestone challenge #188 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 940,
    rewardCoins: 37600,
    rewardGems: 940,
    rewardXP: 9400,
  },
  {
    id: 'ach_exp_189',
    title: 'Achievement Challenge Level #189',
    description: 'Complete match milestone challenge #189 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 945,
    rewardCoins: 37800,
    rewardGems: 945,
    rewardXP: 9450,
  },
  {
    id: 'ach_exp_190',
    title: 'Achievement Challenge Level #190',
    description: 'Complete match milestone challenge #190 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 950,
    rewardCoins: 38000,
    rewardGems: 950,
    rewardXP: 9500,
  },
  {
    id: 'ach_exp_191',
    title: 'Achievement Challenge Level #191',
    description: 'Complete match milestone challenge #191 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 955,
    rewardCoins: 38200,
    rewardGems: 955,
    rewardXP: 9550,
  },
  {
    id: 'ach_exp_192',
    title: 'Achievement Challenge Level #192',
    description: 'Complete match milestone challenge #192 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 960,
    rewardCoins: 38400,
    rewardGems: 960,
    rewardXP: 9600,
  },
  {
    id: 'ach_exp_193',
    title: 'Achievement Challenge Level #193',
    description: 'Complete match milestone challenge #193 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 965,
    rewardCoins: 38600,
    rewardGems: 965,
    rewardXP: 9650,
  },
  {
    id: 'ach_exp_194',
    title: 'Achievement Challenge Level #194',
    description: 'Complete match milestone challenge #194 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 970,
    rewardCoins: 38800,
    rewardGems: 970,
    rewardXP: 9700,
  },
  {
    id: 'ach_exp_195',
    title: 'Achievement Challenge Level #195',
    description: 'Complete match milestone challenge #195 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 975,
    rewardCoins: 39000,
    rewardGems: 975,
    rewardXP: 9750,
  },
  {
    id: 'ach_exp_196',
    title: 'Achievement Challenge Level #196',
    description: 'Complete match milestone challenge #196 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 980,
    rewardCoins: 39200,
    rewardGems: 980,
    rewardXP: 9800,
  },
  {
    id: 'ach_exp_197',
    title: 'Achievement Challenge Level #197',
    description: 'Complete match milestone challenge #197 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 985,
    rewardCoins: 39400,
    rewardGems: 985,
    rewardXP: 9850,
  },
  {
    id: 'ach_exp_198',
    title: 'Achievement Challenge Level #198',
    description: 'Complete match milestone challenge #198 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 990,
    rewardCoins: 39600,
    rewardGems: 990,
    rewardXP: 9900,
  },
  {
    id: 'ach_exp_199',
    title: 'Achievement Challenge Level #199',
    description: 'Complete match milestone challenge #199 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 995,
    rewardCoins: 39800,
    rewardGems: 995,
    rewardXP: 9950,
  },
  {
    id: 'ach_exp_200',
    title: 'Achievement Challenge Level #200',
    description: 'Complete match milestone challenge #200 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1000,
    rewardCoins: 40000,
    rewardGems: 1000,
    rewardXP: 10000,
  },
  {
    id: 'ach_exp_201',
    title: 'Achievement Challenge Level #201',
    description: 'Complete match milestone challenge #201 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1005,
    rewardCoins: 40200,
    rewardGems: 1005,
    rewardXP: 10050,
  },
  {
    id: 'ach_exp_202',
    title: 'Achievement Challenge Level #202',
    description: 'Complete match milestone challenge #202 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1010,
    rewardCoins: 40400,
    rewardGems: 1010,
    rewardXP: 10100,
  },
  {
    id: 'ach_exp_203',
    title: 'Achievement Challenge Level #203',
    description: 'Complete match milestone challenge #203 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1015,
    rewardCoins: 40600,
    rewardGems: 1015,
    rewardXP: 10150,
  },
  {
    id: 'ach_exp_204',
    title: 'Achievement Challenge Level #204',
    description: 'Complete match milestone challenge #204 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1020,
    rewardCoins: 40800,
    rewardGems: 1020,
    rewardXP: 10200,
  },
  {
    id: 'ach_exp_205',
    title: 'Achievement Challenge Level #205',
    description: 'Complete match milestone challenge #205 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1025,
    rewardCoins: 41000,
    rewardGems: 1025,
    rewardXP: 10250,
  },
  {
    id: 'ach_exp_206',
    title: 'Achievement Challenge Level #206',
    description: 'Complete match milestone challenge #206 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1030,
    rewardCoins: 41200,
    rewardGems: 1030,
    rewardXP: 10300,
  },
  {
    id: 'ach_exp_207',
    title: 'Achievement Challenge Level #207',
    description: 'Complete match milestone challenge #207 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1035,
    rewardCoins: 41400,
    rewardGems: 1035,
    rewardXP: 10350,
  },
  {
    id: 'ach_exp_208',
    title: 'Achievement Challenge Level #208',
    description: 'Complete match milestone challenge #208 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1040,
    rewardCoins: 41600,
    rewardGems: 1040,
    rewardXP: 10400,
  },
  {
    id: 'ach_exp_209',
    title: 'Achievement Challenge Level #209',
    description: 'Complete match milestone challenge #209 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1045,
    rewardCoins: 41800,
    rewardGems: 1045,
    rewardXP: 10450,
  },
  {
    id: 'ach_exp_210',
    title: 'Achievement Challenge Level #210',
    description: 'Complete match milestone challenge #210 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1050,
    rewardCoins: 42000,
    rewardGems: 1050,
    rewardXP: 10500,
  },
  {
    id: 'ach_exp_211',
    title: 'Achievement Challenge Level #211',
    description: 'Complete match milestone challenge #211 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1055,
    rewardCoins: 42200,
    rewardGems: 1055,
    rewardXP: 10550,
  },
  {
    id: 'ach_exp_212',
    title: 'Achievement Challenge Level #212',
    description: 'Complete match milestone challenge #212 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1060,
    rewardCoins: 42400,
    rewardGems: 1060,
    rewardXP: 10600,
  },
  {
    id: 'ach_exp_213',
    title: 'Achievement Challenge Level #213',
    description: 'Complete match milestone challenge #213 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1065,
    rewardCoins: 42600,
    rewardGems: 1065,
    rewardXP: 10650,
  },
  {
    id: 'ach_exp_214',
    title: 'Achievement Challenge Level #214',
    description: 'Complete match milestone challenge #214 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1070,
    rewardCoins: 42800,
    rewardGems: 1070,
    rewardXP: 10700,
  },
  {
    id: 'ach_exp_215',
    title: 'Achievement Challenge Level #215',
    description: 'Complete match milestone challenge #215 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1075,
    rewardCoins: 43000,
    rewardGems: 1075,
    rewardXP: 10750,
  },
  {
    id: 'ach_exp_216',
    title: 'Achievement Challenge Level #216',
    description: 'Complete match milestone challenge #216 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1080,
    rewardCoins: 43200,
    rewardGems: 1080,
    rewardXP: 10800,
  },
  {
    id: 'ach_exp_217',
    title: 'Achievement Challenge Level #217',
    description: 'Complete match milestone challenge #217 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1085,
    rewardCoins: 43400,
    rewardGems: 1085,
    rewardXP: 10850,
  },
  {
    id: 'ach_exp_218',
    title: 'Achievement Challenge Level #218',
    description: 'Complete match milestone challenge #218 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1090,
    rewardCoins: 43600,
    rewardGems: 1090,
    rewardXP: 10900,
  },
  {
    id: 'ach_exp_219',
    title: 'Achievement Challenge Level #219',
    description: 'Complete match milestone challenge #219 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1095,
    rewardCoins: 43800,
    rewardGems: 1095,
    rewardXP: 10950,
  },
  {
    id: 'ach_exp_220',
    title: 'Achievement Challenge Level #220',
    description: 'Complete match milestone challenge #220 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1100,
    rewardCoins: 44000,
    rewardGems: 1100,
    rewardXP: 11000,
  },
  {
    id: 'ach_exp_221',
    title: 'Achievement Challenge Level #221',
    description: 'Complete match milestone challenge #221 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1105,
    rewardCoins: 44200,
    rewardGems: 1105,
    rewardXP: 11050,
  },
  {
    id: 'ach_exp_222',
    title: 'Achievement Challenge Level #222',
    description: 'Complete match milestone challenge #222 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1110,
    rewardCoins: 44400,
    rewardGems: 1110,
    rewardXP: 11100,
  },
  {
    id: 'ach_exp_223',
    title: 'Achievement Challenge Level #223',
    description: 'Complete match milestone challenge #223 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1115,
    rewardCoins: 44600,
    rewardGems: 1115,
    rewardXP: 11150,
  },
  {
    id: 'ach_exp_224',
    title: 'Achievement Challenge Level #224',
    description: 'Complete match milestone challenge #224 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1120,
    rewardCoins: 44800,
    rewardGems: 1120,
    rewardXP: 11200,
  },
  {
    id: 'ach_exp_225',
    title: 'Achievement Challenge Level #225',
    description: 'Complete match milestone challenge #225 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1125,
    rewardCoins: 45000,
    rewardGems: 1125,
    rewardXP: 11250,
  },
  {
    id: 'ach_exp_226',
    title: 'Achievement Challenge Level #226',
    description: 'Complete match milestone challenge #226 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1130,
    rewardCoins: 45200,
    rewardGems: 1130,
    rewardXP: 11300,
  },
  {
    id: 'ach_exp_227',
    title: 'Achievement Challenge Level #227',
    description: 'Complete match milestone challenge #227 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1135,
    rewardCoins: 45400,
    rewardGems: 1135,
    rewardXP: 11350,
  },
  {
    id: 'ach_exp_228',
    title: 'Achievement Challenge Level #228',
    description: 'Complete match milestone challenge #228 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1140,
    rewardCoins: 45600,
    rewardGems: 1140,
    rewardXP: 11400,
  },
  {
    id: 'ach_exp_229',
    title: 'Achievement Challenge Level #229',
    description: 'Complete match milestone challenge #229 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1145,
    rewardCoins: 45800,
    rewardGems: 1145,
    rewardXP: 11450,
  },
  {
    id: 'ach_exp_230',
    title: 'Achievement Challenge Level #230',
    description: 'Complete match milestone challenge #230 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1150,
    rewardCoins: 46000,
    rewardGems: 1150,
    rewardXP: 11500,
  },
  {
    id: 'ach_exp_231',
    title: 'Achievement Challenge Level #231',
    description: 'Complete match milestone challenge #231 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1155,
    rewardCoins: 46200,
    rewardGems: 1155,
    rewardXP: 11550,
  },
  {
    id: 'ach_exp_232',
    title: 'Achievement Challenge Level #232',
    description: 'Complete match milestone challenge #232 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1160,
    rewardCoins: 46400,
    rewardGems: 1160,
    rewardXP: 11600,
  },
  {
    id: 'ach_exp_233',
    title: 'Achievement Challenge Level #233',
    description: 'Complete match milestone challenge #233 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1165,
    rewardCoins: 46600,
    rewardGems: 1165,
    rewardXP: 11650,
  },
  {
    id: 'ach_exp_234',
    title: 'Achievement Challenge Level #234',
    description: 'Complete match milestone challenge #234 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1170,
    rewardCoins: 46800,
    rewardGems: 1170,
    rewardXP: 11700,
  },
  {
    id: 'ach_exp_235',
    title: 'Achievement Challenge Level #235',
    description: 'Complete match milestone challenge #235 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1175,
    rewardCoins: 47000,
    rewardGems: 1175,
    rewardXP: 11750,
  },
  {
    id: 'ach_exp_236',
    title: 'Achievement Challenge Level #236',
    description: 'Complete match milestone challenge #236 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1180,
    rewardCoins: 47200,
    rewardGems: 1180,
    rewardXP: 11800,
  },
  {
    id: 'ach_exp_237',
    title: 'Achievement Challenge Level #237',
    description: 'Complete match milestone challenge #237 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1185,
    rewardCoins: 47400,
    rewardGems: 1185,
    rewardXP: 11850,
  },
  {
    id: 'ach_exp_238',
    title: 'Achievement Challenge Level #238',
    description: 'Complete match milestone challenge #238 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1190,
    rewardCoins: 47600,
    rewardGems: 1190,
    rewardXP: 11900,
  },
  {
    id: 'ach_exp_239',
    title: 'Achievement Challenge Level #239',
    description: 'Complete match milestone challenge #239 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1195,
    rewardCoins: 47800,
    rewardGems: 1195,
    rewardXP: 11950,
  },
  {
    id: 'ach_exp_240',
    title: 'Achievement Challenge Level #240',
    description: 'Complete match milestone challenge #240 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1200,
    rewardCoins: 48000,
    rewardGems: 1200,
    rewardXP: 12000,
  },
  {
    id: 'ach_exp_241',
    title: 'Achievement Challenge Level #241',
    description: 'Complete match milestone challenge #241 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1205,
    rewardCoins: 48200,
    rewardGems: 1205,
    rewardXP: 12050,
  },
  {
    id: 'ach_exp_242',
    title: 'Achievement Challenge Level #242',
    description: 'Complete match milestone challenge #242 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1210,
    rewardCoins: 48400,
    rewardGems: 1210,
    rewardXP: 12100,
  },
  {
    id: 'ach_exp_243',
    title: 'Achievement Challenge Level #243',
    description: 'Complete match milestone challenge #243 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1215,
    rewardCoins: 48600,
    rewardGems: 1215,
    rewardXP: 12150,
  },
  {
    id: 'ach_exp_244',
    title: 'Achievement Challenge Level #244',
    description: 'Complete match milestone challenge #244 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1220,
    rewardCoins: 48800,
    rewardGems: 1220,
    rewardXP: 12200,
  },
  {
    id: 'ach_exp_245',
    title: 'Achievement Challenge Level #245',
    description: 'Complete match milestone challenge #245 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1225,
    rewardCoins: 49000,
    rewardGems: 1225,
    rewardXP: 12250,
  },
  {
    id: 'ach_exp_246',
    title: 'Achievement Challenge Level #246',
    description: 'Complete match milestone challenge #246 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1230,
    rewardCoins: 49200,
    rewardGems: 1230,
    rewardXP: 12300,
  },
  {
    id: 'ach_exp_247',
    title: 'Achievement Challenge Level #247',
    description: 'Complete match milestone challenge #247 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1235,
    rewardCoins: 49400,
    rewardGems: 1235,
    rewardXP: 12350,
  },
  {
    id: 'ach_exp_248',
    title: 'Achievement Challenge Level #248',
    description: 'Complete match milestone challenge #248 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1240,
    rewardCoins: 49600,
    rewardGems: 1240,
    rewardXP: 12400,
  },
  {
    id: 'ach_exp_249',
    title: 'Achievement Challenge Level #249',
    description: 'Complete match milestone challenge #249 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1245,
    rewardCoins: 49800,
    rewardGems: 1245,
    rewardXP: 12450,
  },
  {
    id: 'ach_exp_250',
    title: 'Achievement Challenge Level #250',
    description: 'Complete match milestone challenge #250 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1250,
    rewardCoins: 50000,
    rewardGems: 1250,
    rewardXP: 12500,
  },
  {
    id: 'ach_exp_251',
    title: 'Achievement Challenge Level #251',
    description: 'Complete match milestone challenge #251 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1255,
    rewardCoins: 50200,
    rewardGems: 1255,
    rewardXP: 12550,
  },
  {
    id: 'ach_exp_252',
    title: 'Achievement Challenge Level #252',
    description: 'Complete match milestone challenge #252 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1260,
    rewardCoins: 50400,
    rewardGems: 1260,
    rewardXP: 12600,
  },
  {
    id: 'ach_exp_253',
    title: 'Achievement Challenge Level #253',
    description: 'Complete match milestone challenge #253 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1265,
    rewardCoins: 50600,
    rewardGems: 1265,
    rewardXP: 12650,
  },
  {
    id: 'ach_exp_254',
    title: 'Achievement Challenge Level #254',
    description: 'Complete match milestone challenge #254 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1270,
    rewardCoins: 50800,
    rewardGems: 1270,
    rewardXP: 12700,
  },
  {
    id: 'ach_exp_255',
    title: 'Achievement Challenge Level #255',
    description: 'Complete match milestone challenge #255 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1275,
    rewardCoins: 51000,
    rewardGems: 1275,
    rewardXP: 12750,
  },
  {
    id: 'ach_exp_256',
    title: 'Achievement Challenge Level #256',
    description: 'Complete match milestone challenge #256 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1280,
    rewardCoins: 51200,
    rewardGems: 1280,
    rewardXP: 12800,
  },
  {
    id: 'ach_exp_257',
    title: 'Achievement Challenge Level #257',
    description: 'Complete match milestone challenge #257 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1285,
    rewardCoins: 51400,
    rewardGems: 1285,
    rewardXP: 12850,
  },
  {
    id: 'ach_exp_258',
    title: 'Achievement Challenge Level #258',
    description: 'Complete match milestone challenge #258 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1290,
    rewardCoins: 51600,
    rewardGems: 1290,
    rewardXP: 12900,
  },
  {
    id: 'ach_exp_259',
    title: 'Achievement Challenge Level #259',
    description: 'Complete match milestone challenge #259 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1295,
    rewardCoins: 51800,
    rewardGems: 1295,
    rewardXP: 12950,
  },
  {
    id: 'ach_exp_260',
    title: 'Achievement Challenge Level #260',
    description: 'Complete match milestone challenge #260 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1300,
    rewardCoins: 52000,
    rewardGems: 1300,
    rewardXP: 13000,
  },
  {
    id: 'ach_exp_261',
    title: 'Achievement Challenge Level #261',
    description: 'Complete match milestone challenge #261 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1305,
    rewardCoins: 52200,
    rewardGems: 1305,
    rewardXP: 13050,
  },
  {
    id: 'ach_exp_262',
    title: 'Achievement Challenge Level #262',
    description: 'Complete match milestone challenge #262 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1310,
    rewardCoins: 52400,
    rewardGems: 1310,
    rewardXP: 13100,
  },
  {
    id: 'ach_exp_263',
    title: 'Achievement Challenge Level #263',
    description: 'Complete match milestone challenge #263 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1315,
    rewardCoins: 52600,
    rewardGems: 1315,
    rewardXP: 13150,
  },
  {
    id: 'ach_exp_264',
    title: 'Achievement Challenge Level #264',
    description: 'Complete match milestone challenge #264 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1320,
    rewardCoins: 52800,
    rewardGems: 1320,
    rewardXP: 13200,
  },
  {
    id: 'ach_exp_265',
    title: 'Achievement Challenge Level #265',
    description: 'Complete match milestone challenge #265 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1325,
    rewardCoins: 53000,
    rewardGems: 1325,
    rewardXP: 13250,
  },
  {
    id: 'ach_exp_266',
    title: 'Achievement Challenge Level #266',
    description: 'Complete match milestone challenge #266 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1330,
    rewardCoins: 53200,
    rewardGems: 1330,
    rewardXP: 13300,
  },
  {
    id: 'ach_exp_267',
    title: 'Achievement Challenge Level #267',
    description: 'Complete match milestone challenge #267 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1335,
    rewardCoins: 53400,
    rewardGems: 1335,
    rewardXP: 13350,
  },
  {
    id: 'ach_exp_268',
    title: 'Achievement Challenge Level #268',
    description: 'Complete match milestone challenge #268 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1340,
    rewardCoins: 53600,
    rewardGems: 1340,
    rewardXP: 13400,
  },
  {
    id: 'ach_exp_269',
    title: 'Achievement Challenge Level #269',
    description: 'Complete match milestone challenge #269 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1345,
    rewardCoins: 53800,
    rewardGems: 1345,
    rewardXP: 13450,
  },
  {
    id: 'ach_exp_270',
    title: 'Achievement Challenge Level #270',
    description: 'Complete match milestone challenge #270 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1350,
    rewardCoins: 54000,
    rewardGems: 1350,
    rewardXP: 13500,
  },
  {
    id: 'ach_exp_271',
    title: 'Achievement Challenge Level #271',
    description: 'Complete match milestone challenge #271 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1355,
    rewardCoins: 54200,
    rewardGems: 1355,
    rewardXP: 13550,
  },
  {
    id: 'ach_exp_272',
    title: 'Achievement Challenge Level #272',
    description: 'Complete match milestone challenge #272 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1360,
    rewardCoins: 54400,
    rewardGems: 1360,
    rewardXP: 13600,
  },
  {
    id: 'ach_exp_273',
    title: 'Achievement Challenge Level #273',
    description: 'Complete match milestone challenge #273 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1365,
    rewardCoins: 54600,
    rewardGems: 1365,
    rewardXP: 13650,
  },
  {
    id: 'ach_exp_274',
    title: 'Achievement Challenge Level #274',
    description: 'Complete match milestone challenge #274 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1370,
    rewardCoins: 54800,
    rewardGems: 1370,
    rewardXP: 13700,
  },
  {
    id: 'ach_exp_275',
    title: 'Achievement Challenge Level #275',
    description: 'Complete match milestone challenge #275 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1375,
    rewardCoins: 55000,
    rewardGems: 1375,
    rewardXP: 13750,
  },
  {
    id: 'ach_exp_276',
    title: 'Achievement Challenge Level #276',
    description: 'Complete match milestone challenge #276 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1380,
    rewardCoins: 55200,
    rewardGems: 1380,
    rewardXP: 13800,
  },
  {
    id: 'ach_exp_277',
    title: 'Achievement Challenge Level #277',
    description: 'Complete match milestone challenge #277 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1385,
    rewardCoins: 55400,
    rewardGems: 1385,
    rewardXP: 13850,
  },
  {
    id: 'ach_exp_278',
    title: 'Achievement Challenge Level #278',
    description: 'Complete match milestone challenge #278 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1390,
    rewardCoins: 55600,
    rewardGems: 1390,
    rewardXP: 13900,
  },
  {
    id: 'ach_exp_279',
    title: 'Achievement Challenge Level #279',
    description: 'Complete match milestone challenge #279 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1395,
    rewardCoins: 55800,
    rewardGems: 1395,
    rewardXP: 13950,
  },
  {
    id: 'ach_exp_280',
    title: 'Achievement Challenge Level #280',
    description: 'Complete match milestone challenge #280 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1400,
    rewardCoins: 56000,
    rewardGems: 1400,
    rewardXP: 14000,
  },
  {
    id: 'ach_exp_281',
    title: 'Achievement Challenge Level #281',
    description: 'Complete match milestone challenge #281 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1405,
    rewardCoins: 56200,
    rewardGems: 1405,
    rewardXP: 14050,
  },
  {
    id: 'ach_exp_282',
    title: 'Achievement Challenge Level #282',
    description: 'Complete match milestone challenge #282 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1410,
    rewardCoins: 56400,
    rewardGems: 1410,
    rewardXP: 14100,
  },
  {
    id: 'ach_exp_283',
    title: 'Achievement Challenge Level #283',
    description: 'Complete match milestone challenge #283 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1415,
    rewardCoins: 56600,
    rewardGems: 1415,
    rewardXP: 14150,
  },
  {
    id: 'ach_exp_284',
    title: 'Achievement Challenge Level #284',
    description: 'Complete match milestone challenge #284 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1420,
    rewardCoins: 56800,
    rewardGems: 1420,
    rewardXP: 14200,
  },
  {
    id: 'ach_exp_285',
    title: 'Achievement Challenge Level #285',
    description: 'Complete match milestone challenge #285 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1425,
    rewardCoins: 57000,
    rewardGems: 1425,
    rewardXP: 14250,
  },
  {
    id: 'ach_exp_286',
    title: 'Achievement Challenge Level #286',
    description: 'Complete match milestone challenge #286 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1430,
    rewardCoins: 57200,
    rewardGems: 1430,
    rewardXP: 14300,
  },
  {
    id: 'ach_exp_287',
    title: 'Achievement Challenge Level #287',
    description: 'Complete match milestone challenge #287 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1435,
    rewardCoins: 57400,
    rewardGems: 1435,
    rewardXP: 14350,
  },
  {
    id: 'ach_exp_288',
    title: 'Achievement Challenge Level #288',
    description: 'Complete match milestone challenge #288 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1440,
    rewardCoins: 57600,
    rewardGems: 1440,
    rewardXP: 14400,
  },
  {
    id: 'ach_exp_289',
    title: 'Achievement Challenge Level #289',
    description: 'Complete match milestone challenge #289 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1445,
    rewardCoins: 57800,
    rewardGems: 1445,
    rewardXP: 14450,
  },
  {
    id: 'ach_exp_290',
    title: 'Achievement Challenge Level #290',
    description: 'Complete match milestone challenge #290 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1450,
    rewardCoins: 58000,
    rewardGems: 1450,
    rewardXP: 14500,
  },
  {
    id: 'ach_exp_291',
    title: 'Achievement Challenge Level #291',
    description: 'Complete match milestone challenge #291 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1455,
    rewardCoins: 58200,
    rewardGems: 1455,
    rewardXP: 14550,
  },
  {
    id: 'ach_exp_292',
    title: 'Achievement Challenge Level #292',
    description: 'Complete match milestone challenge #292 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1460,
    rewardCoins: 58400,
    rewardGems: 1460,
    rewardXP: 14600,
  },
  {
    id: 'ach_exp_293',
    title: 'Achievement Challenge Level #293',
    description: 'Complete match milestone challenge #293 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1465,
    rewardCoins: 58600,
    rewardGems: 1465,
    rewardXP: 14650,
  },
  {
    id: 'ach_exp_294',
    title: 'Achievement Challenge Level #294',
    description: 'Complete match milestone challenge #294 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1470,
    rewardCoins: 58800,
    rewardGems: 1470,
    rewardXP: 14700,
  },
  {
    id: 'ach_exp_295',
    title: 'Achievement Challenge Level #295',
    description: 'Complete match milestone challenge #295 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1475,
    rewardCoins: 59000,
    rewardGems: 1475,
    rewardXP: 14750,
  },
  {
    id: 'ach_exp_296',
    title: 'Achievement Challenge Level #296',
    description: 'Complete match milestone challenge #296 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1480,
    rewardCoins: 59200,
    rewardGems: 1480,
    rewardXP: 14800,
  },
  {
    id: 'ach_exp_297',
    title: 'Achievement Challenge Level #297',
    description: 'Complete match milestone challenge #297 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1485,
    rewardCoins: 59400,
    rewardGems: 1485,
    rewardXP: 14850,
  },
  {
    id: 'ach_exp_298',
    title: 'Achievement Challenge Level #298',
    description: 'Complete match milestone challenge #298 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1490,
    rewardCoins: 59600,
    rewardGems: 1490,
    rewardXP: 14900,
  },
  {
    id: 'ach_exp_299',
    title: 'Achievement Challenge Level #299',
    description: 'Complete match milestone challenge #299 in online multiplayer matches.',
    category: 'WINS',
    icon: '⭐',
    targetValue: 1495,
    rewardCoins: 59800,
    rewardGems: 1495,
    rewardXP: 14950,
  },
  {
    id: 'ach_exp_300',
    title: 'Achievement Challenge Level #300',
    description: 'Complete match milestone challenge #300 in online multiplayer matches.',
    category: 'GAMEPLAY',
    icon: '🏆',
    targetValue: 1500,
    rewardCoins: 60000,
    rewardGems: 1500,
    rewardXP: 15000,
  },
];
