import { AchievementDef } from './achievements.js';

export const EXPLICIT_ACHIEVEMENTS_FULL_500: AchievementDef[] = [
  { id: 'full_ach_1', title: 'Novice Ludo Player', description: 'Complete 1 match in online multiplayer.', category: 'WINS', icon: '🏆', targetValue: 1, rewardCoins: 500, rewardGems: 10, rewardXP: 100 },
  { id: 'full_ach_2', title: 'Skilled Ludo Player', description: 'Complete 2 matches in online multiplayer.', category: 'WINS', icon: '🏆', targetValue: 2, rewardCoins: 1000, rewardGems: 20, rewardXP: 200 },
  { id: 'full_ach_3', title: 'Experienced Ludo Player', description: 'Complete 3 matches in online multiplayer.', category: 'WINS', icon: '🏆', targetValue: 3, rewardCoins: 1500, rewardGems: 30, rewardXP: 300 },
  { id: 'full_ach_4', title: 'Advanced Ludo Player', description: 'Complete 4 matches in online multiplayer.', category: 'WINS', icon: '🏆', targetValue: 4, rewardCoins: 2000, rewardGems: 40, rewardXP: 400 },
  { id: 'full_ach_5', title: 'Master Ludo Player', description: 'Complete 5 matches in online multiplayer.', category: 'WINS', icon: '🏆', targetValue: 5, rewardCoins: 2500, rewardGems: 50, rewardXP: 500 },
  { id: 'full_ach_6', title: 'Elite Ludo Competitor', description: 'Complete 6 matches in online multiplayer.', category: 'WINS', icon: '⭐', targetValue: 6, rewardCoins: 3000, rewardGems: 60, rewardXP: 600 },
  { id: 'full_ach_7', title: 'Grandmaster Ludo Competitor', description: 'Complete 7 matches in online multiplayer.', category: 'WINS', icon: '⭐', targetValue: 7, rewardCoins: 3500, rewardGems: 70, rewardXP: 700 },
  { id: 'full_ach_8', title: 'Champion of the Board', description: 'Complete 8 matches in online multiplayer.', category: 'WINS', icon: '⭐', targetValue: 8, rewardCoins: 4000, rewardGems: 80, rewardXP: 800 },
  { id: 'full_ach_9', title: 'Unstoppable Force', description: 'Complete 9 matches in online multiplayer.', category: 'WINS', icon: '⭐', targetValue: 9, rewardCoins: 4500, rewardGems: 90, rewardXP: 900 },
  { id: 'full_ach_10', title: 'Ludo Legend Standard', description: 'Complete 10 matches in online multiplayer.', category: 'WINS', icon: '👑', targetValue: 10, rewardCoins: 5000, rewardGems: 100, rewardXP: 1000 },
  { id: 'full_ach_11', title: 'Pawn Striker Level 1', description: 'Capture 1 opponent pawn.', category: 'GAMEPLAY', icon: '🎯', targetValue: 1, rewardCoins: 200, rewardGems: 5, rewardXP: 50 },
  { id: 'full_ach_12', title: 'Pawn Striker Level 2', description: 'Capture 2 opponent pawns.', category: 'GAMEPLAY', icon: '🎯', targetValue: 2, rewardCoins: 400, rewardGems: 10, rewardXP: 100 },
  { id: 'full_ach_13', title: 'Pawn Striker Level 3', description: 'Capture 3 opponent pawns.', category: 'GAMEPLAY', icon: '🎯', targetValue: 3, rewardCoins: 600, rewardGems: 15, rewardXP: 150 },
  { id: 'full_ach_14', title: 'Pawn Striker Level 4', description: 'Capture 4 opponent pawns.', category: 'GAMEPLAY', icon: '🎯', targetValue: 4, rewardCoins: 800, rewardGems: 20, rewardXP: 200 },
  { id: 'full_ach_15', title: 'Pawn Striker Level 5', description: 'Capture 5 opponent pawns.', category: 'GAMEPLAY', icon: '🎯', targetValue: 5, rewardCoins: 1000, rewardGems: 25, rewardXP: 250 },
  { id: 'full_ach_16', title: 'Pawn Hunter Level 6', description: 'Capture 6 opponent pawns.', category: 'GAMEPLAY', icon: '⚔️', targetValue: 6, rewardCoins: 1200, rewardGems: 30, rewardXP: 300 },
  { id: 'full_ach_17', title: 'Pawn Hunter Level 7', description: 'Capture 7 opponent pawns.', category: 'GAMEPLAY', icon: '⚔️', targetValue: 7, rewardCoins: 1400, rewardGems: 35, rewardXP: 350 },
  { id: 'full_ach_18', title: 'Pawn Hunter Level 8', description: 'Capture 8 opponent pawns.', category: 'GAMEPLAY', icon: '⚔️', targetValue: 8, rewardCoins: 1600, rewardGems: 40, rewardXP: 400 },
  { id: 'full_ach_19', title: 'Pawn Hunter Level 9', description: 'Capture 9 opponent pawns.', category: 'GAMEPLAY', icon: '⚔️', targetValue: 9, rewardCoins: 1800, rewardGems: 45, rewardXP: 450 },
  { id: 'full_ach_20', title: 'Pawn Hunter Level 10', description: 'Capture 10 opponent pawns.', category: 'GAMEPLAY', icon: '⚔️', targetValue: 10, rewardCoins: 2000, rewardGems: 50, rewardXP: 500 },
  { id: 'full_ach_21', title: 'Dice Master Tier 1', description: 'Roll a 6 five times.', category: 'GAMEPLAY', icon: '🎲', targetValue: 5, rewardCoins: 500, rewardGems: 10, rewardXP: 100 },
  { id: 'full_ach_22', title: 'Dice Master Tier 2', description: 'Roll a 6 ten times.', category: 'GAMEPLAY', icon: '🎲', targetValue: 10, rewardCoins: 1000, rewardGems: 20, rewardXP: 200 },
  { id: 'full_ach_23', title: 'Dice Master Tier 3', description: 'Roll a 6 fifteen times.', category: 'GAMEPLAY', icon: '🎲', targetValue: 15, rewardCoins: 1500, rewardGems: 30, rewardXP: 300 },
  { id: 'full_ach_24', title: 'Dice Master Tier 4', description: 'Roll a 6 twenty times.', category: 'GAMEPLAY', icon: '🎲', targetValue: 20, rewardCoins: 2000, rewardGems: 40, rewardXP: 400 },
  { id: 'full_ach_25', title: 'Dice Master Tier 5', description: 'Roll a 6 twenty-five times.', category: 'GAMEPLAY', icon: '🎲', targetValue: 25, rewardCoins: 2500, rewardGems: 50, rewardXP: 500 },
];
