import { PlayerColor } from '../types/game.js';

export interface TelemetryFrameRecord {
  frameId: string;
  turnNumber: number;
  activeColor: PlayerColor;
  diceRoll: number;
  tokenId: string;
  startStep: number;
  endStep: number;
  isCaptureEvent: boolean;
  isHomeEvent: boolean;
  executionTimeMs: number;
  serverTimestamp: number;
}

export const ENGINE_TELEMETRY_LOGS_DATABASE: TelemetryFrameRecord[] = [
  {
    frameId: 'frame_1',
    turnNumber: 1,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 1,
    endStep: 3,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.94,
    serverTimestamp: 1787652387049,
  },
  {
    frameId: 'frame_2',
    turnNumber: 2,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 2,
    endStep: 5,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.58,
    serverTimestamp: 1787652388049,
  },
  {
    frameId: 'frame_3',
    turnNumber: 3,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 3,
    endStep: 7,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.94,
    serverTimestamp: 1787652389049,
  },
  {
    frameId: 'frame_4',
    turnNumber: 4,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 4,
    endStep: 9,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.90,
    serverTimestamp: 1787652390049,
  },
  {
    frameId: 'frame_5',
    turnNumber: 5,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 5,
    endStep: 11,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.45,
    serverTimestamp: 1787652391049,
  },
  {
    frameId: 'frame_6',
    turnNumber: 6,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 6,
    endStep: 7,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.81,
    serverTimestamp: 1787652392049,
  },
  {
    frameId: 'frame_7',
    turnNumber: 7,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 7,
    endStep: 9,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.57,
    serverTimestamp: 1787652393049,
  },
  {
    frameId: 'frame_8',
    turnNumber: 8,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 8,
    endStep: 11,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.08,
    serverTimestamp: 1787652394049,
  },
  {
    frameId: 'frame_9',
    turnNumber: 9,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 9,
    endStep: 13,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.41,
    serverTimestamp: 1787652395049,
  },
  {
    frameId: 'frame_10',
    turnNumber: 10,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 10,
    endStep: 15,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.87,
    serverTimestamp: 1787652396049,
  },
  {
    frameId: 'frame_11',
    turnNumber: 11,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 11,
    endStep: 17,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.25,
    serverTimestamp: 1787652397049,
  },
  {
    frameId: 'frame_12',
    turnNumber: 12,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 12,
    endStep: 13,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.73,
    serverTimestamp: 1787652398049,
  },
  {
    frameId: 'frame_13',
    turnNumber: 13,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 13,
    endStep: 15,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 1.34,
    serverTimestamp: 1787652399049,
  },
  {
    frameId: 'frame_14',
    turnNumber: 14,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 14,
    endStep: 17,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.71,
    serverTimestamp: 1787652400049,
  },
  {
    frameId: 'frame_15',
    turnNumber: 15,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 15,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.80,
    serverTimestamp: 1787652401049,
  },
  {
    frameId: 'frame_16',
    turnNumber: 16,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 16,
    endStep: 21,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.32,
    serverTimestamp: 1787652402049,
  },
  {
    frameId: 'frame_17',
    turnNumber: 17,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 17,
    endStep: 23,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.20,
    serverTimestamp: 1787652403049,
  },
  {
    frameId: 'frame_18',
    turnNumber: 18,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 18,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.36,
    serverTimestamp: 1787652404049,
  },
  {
    frameId: 'frame_19',
    turnNumber: 19,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 19,
    endStep: 21,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.08,
    serverTimestamp: 1787652405049,
  },
  {
    frameId: 'frame_20',
    turnNumber: 20,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 20,
    endStep: 23,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.83,
    serverTimestamp: 1787652406049,
  },
  {
    frameId: 'frame_21',
    turnNumber: 21,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 21,
    endStep: 25,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 4.78,
    serverTimestamp: 1787652407049,
  },
  {
    frameId: 'frame_22',
    turnNumber: 22,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 22,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.32,
    serverTimestamp: 1787652408049,
  },
  {
    frameId: 'frame_23',
    turnNumber: 23,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 23,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 6.00,
    serverTimestamp: 1787652409049,
  },
  {
    frameId: 'frame_24',
    turnNumber: 24,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 24,
    endStep: 25,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.04,
    serverTimestamp: 1787652410049,
  },
  {
    frameId: 'frame_25',
    turnNumber: 25,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 25,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.01,
    serverTimestamp: 1787652411049,
  },
  {
    frameId: 'frame_26',
    turnNumber: 26,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 26,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 3.10,
    serverTimestamp: 1787652412049,
  },
  {
    frameId: 'frame_27',
    turnNumber: 27,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 27,
    endStep: 31,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.50,
    serverTimestamp: 1787652413049,
  },
  {
    frameId: 'frame_28',
    turnNumber: 28,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 28,
    endStep: 33,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.31,
    serverTimestamp: 1787652414049,
  },
  {
    frameId: 'frame_29',
    turnNumber: 29,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 29,
    endStep: 35,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.00,
    serverTimestamp: 1787652415049,
  },
  {
    frameId: 'frame_30',
    turnNumber: 30,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 30,
    endStep: 31,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.84,
    serverTimestamp: 1787652416049,
  },
  {
    frameId: 'frame_31',
    turnNumber: 31,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 31,
    endStep: 33,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.90,
    serverTimestamp: 1787652417049,
  },
  {
    frameId: 'frame_32',
    turnNumber: 32,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 32,
    endStep: 35,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.30,
    serverTimestamp: 1787652418049,
  },
  {
    frameId: 'frame_33',
    turnNumber: 33,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 33,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.84,
    serverTimestamp: 1787652419049,
  },
  {
    frameId: 'frame_34',
    turnNumber: 34,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 34,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.91,
    serverTimestamp: 1787652420049,
  },
  {
    frameId: 'frame_35',
    turnNumber: 35,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 35,
    endStep: 41,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 4.87,
    serverTimestamp: 1787652421049,
  },
  {
    frameId: 'frame_36',
    turnNumber: 36,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 36,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.37,
    serverTimestamp: 1787652422049,
  },
  {
    frameId: 'frame_37',
    turnNumber: 37,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 37,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.25,
    serverTimestamp: 1787652423049,
  },
  {
    frameId: 'frame_38',
    turnNumber: 38,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 38,
    endStep: 41,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.19,
    serverTimestamp: 1787652424049,
  },
  {
    frameId: 'frame_39',
    turnNumber: 39,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 39,
    endStep: 43,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 3.32,
    serverTimestamp: 1787652425049,
  },
  {
    frameId: 'frame_40',
    turnNumber: 40,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 40,
    endStep: 45,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.87,
    serverTimestamp: 1787652426049,
  },
  {
    frameId: 'frame_41',
    turnNumber: 41,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 41,
    endStep: 47,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.31,
    serverTimestamp: 1787652427049,
  },
  {
    frameId: 'frame_42',
    turnNumber: 42,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 42,
    endStep: 43,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 4.60,
    serverTimestamp: 1787652428049,
  },
  {
    frameId: 'frame_43',
    turnNumber: 43,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 43,
    endStep: 45,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.05,
    serverTimestamp: 1787652429049,
  },
  {
    frameId: 'frame_44',
    turnNumber: 44,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 44,
    endStep: 47,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.92,
    serverTimestamp: 1787652430049,
  },
  {
    frameId: 'frame_45',
    turnNumber: 45,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 45,
    endStep: 49,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.58,
    serverTimestamp: 1787652431049,
  },
  {
    frameId: 'frame_46',
    turnNumber: 46,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 46,
    endStep: 51,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.04,
    serverTimestamp: 1787652432049,
  },
  {
    frameId: 'frame_47',
    turnNumber: 47,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 47,
    endStep: 1,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.47,
    serverTimestamp: 1787652433049,
  },
  {
    frameId: 'frame_48',
    turnNumber: 48,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 48,
    endStep: 49,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.43,
    serverTimestamp: 1787652434049,
  },
  {
    frameId: 'frame_49',
    turnNumber: 49,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 49,
    endStep: 51,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.37,
    serverTimestamp: 1787652435049,
  },
  {
    frameId: 'frame_50',
    turnNumber: 50,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 50,
    endStep: 1,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.94,
    serverTimestamp: 1787652436049,
  },
  {
    frameId: 'frame_51',
    turnNumber: 51,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 51,
    endStep: 3,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.07,
    serverTimestamp: 1787652437049,
  },
  {
    frameId: 'frame_52',
    turnNumber: 52,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 0,
    endStep: 5,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 2.75,
    serverTimestamp: 1787652438049,
  },
  {
    frameId: 'frame_53',
    turnNumber: 53,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 1,
    endStep: 7,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.65,
    serverTimestamp: 1787652439049,
  },
  {
    frameId: 'frame_54',
    turnNumber: 54,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 2,
    endStep: 3,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.41,
    serverTimestamp: 1787652440049,
  },
  {
    frameId: 'frame_55',
    turnNumber: 55,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 3,
    endStep: 5,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.92,
    serverTimestamp: 1787652441049,
  },
  {
    frameId: 'frame_56',
    turnNumber: 56,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 4,
    endStep: 7,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 5.21,
    serverTimestamp: 1787652442049,
  },
  {
    frameId: 'frame_57',
    turnNumber: 57,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 5,
    endStep: 9,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.59,
    serverTimestamp: 1787652443049,
  },
  {
    frameId: 'frame_58',
    turnNumber: 58,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 6,
    endStep: 11,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.21,
    serverTimestamp: 1787652444049,
  },
  {
    frameId: 'frame_59',
    turnNumber: 59,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 7,
    endStep: 13,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.08,
    serverTimestamp: 1787652445049,
  },
  {
    frameId: 'frame_60',
    turnNumber: 60,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 8,
    endStep: 9,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.58,
    serverTimestamp: 1787652446049,
  },
  {
    frameId: 'frame_61',
    turnNumber: 61,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 9,
    endStep: 11,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.95,
    serverTimestamp: 1787652447049,
  },
  {
    frameId: 'frame_62',
    turnNumber: 62,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 10,
    endStep: 13,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.76,
    serverTimestamp: 1787652448049,
  },
  {
    frameId: 'frame_63',
    turnNumber: 63,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 11,
    endStep: 15,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.18,
    serverTimestamp: 1787652449049,
  },
  {
    frameId: 'frame_64',
    turnNumber: 64,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 12,
    endStep: 17,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.14,
    serverTimestamp: 1787652450049,
  },
  {
    frameId: 'frame_65',
    turnNumber: 65,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 13,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 2.80,
    serverTimestamp: 1787652451049,
  },
  {
    frameId: 'frame_66',
    turnNumber: 66,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 14,
    endStep: 15,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.08,
    serverTimestamp: 1787652452049,
  },
  {
    frameId: 'frame_67',
    turnNumber: 67,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 15,
    endStep: 17,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.89,
    serverTimestamp: 1787652453049,
  },
  {
    frameId: 'frame_68',
    turnNumber: 68,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 16,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.60,
    serverTimestamp: 1787652454049,
  },
  {
    frameId: 'frame_69',
    turnNumber: 69,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 17,
    endStep: 21,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.69,
    serverTimestamp: 1787652455049,
  },
  {
    frameId: 'frame_70',
    turnNumber: 70,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 18,
    endStep: 23,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 5.76,
    serverTimestamp: 1787652456049,
  },
  {
    frameId: 'frame_71',
    turnNumber: 71,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 19,
    endStep: 25,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.83,
    serverTimestamp: 1787652457049,
  },
  {
    frameId: 'frame_72',
    turnNumber: 72,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 20,
    endStep: 21,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.72,
    serverTimestamp: 1787652458049,
  },
  {
    frameId: 'frame_73',
    turnNumber: 73,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 21,
    endStep: 23,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.34,
    serverTimestamp: 1787652459049,
  },
  {
    frameId: 'frame_74',
    turnNumber: 74,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 22,
    endStep: 25,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.97,
    serverTimestamp: 1787652460049,
  },
  {
    frameId: 'frame_75',
    turnNumber: 75,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 23,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.11,
    serverTimestamp: 1787652461049,
  },
  {
    frameId: 'frame_76',
    turnNumber: 76,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 24,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.18,
    serverTimestamp: 1787652462049,
  },
  {
    frameId: 'frame_77',
    turnNumber: 77,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 25,
    endStep: 31,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.78,
    serverTimestamp: 1787652463049,
  },
  {
    frameId: 'frame_78',
    turnNumber: 78,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 26,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 5.80,
    serverTimestamp: 1787652464049,
  },
  {
    frameId: 'frame_79',
    turnNumber: 79,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 27,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.39,
    serverTimestamp: 1787652465049,
  },
  {
    frameId: 'frame_80',
    turnNumber: 80,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 28,
    endStep: 31,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.60,
    serverTimestamp: 1787652466049,
  },
  {
    frameId: 'frame_81',
    turnNumber: 81,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 29,
    endStep: 33,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.88,
    serverTimestamp: 1787652467049,
  },
  {
    frameId: 'frame_82',
    turnNumber: 82,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 30,
    endStep: 35,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.29,
    serverTimestamp: 1787652468049,
  },
  {
    frameId: 'frame_83',
    turnNumber: 83,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 31,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.80,
    serverTimestamp: 1787652469049,
  },
  {
    frameId: 'frame_84',
    turnNumber: 84,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 32,
    endStep: 33,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 4.05,
    serverTimestamp: 1787652470050,
  },
  {
    frameId: 'frame_85',
    turnNumber: 85,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 33,
    endStep: 35,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.42,
    serverTimestamp: 1787652471050,
  },
  {
    frameId: 'frame_86',
    turnNumber: 86,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 34,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.20,
    serverTimestamp: 1787652472050,
  },
  {
    frameId: 'frame_87',
    turnNumber: 87,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 35,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.01,
    serverTimestamp: 1787652473050,
  },
  {
    frameId: 'frame_88',
    turnNumber: 88,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 36,
    endStep: 41,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.71,
    serverTimestamp: 1787652474050,
  },
  {
    frameId: 'frame_89',
    turnNumber: 89,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 37,
    endStep: 43,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.68,
    serverTimestamp: 1787652475050,
  },
  {
    frameId: 'frame_90',
    turnNumber: 90,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 38,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.28,
    serverTimestamp: 1787652476050,
  },
  {
    frameId: 'frame_91',
    turnNumber: 91,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 39,
    endStep: 41,
    isCaptureEvent: true,
    isHomeEvent: true,
    executionTimeMs: 1.28,
    serverTimestamp: 1787652477050,
  },
  {
    frameId: 'frame_92',
    turnNumber: 92,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 40,
    endStep: 43,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.65,
    serverTimestamp: 1787652478050,
  },
  {
    frameId: 'frame_93',
    turnNumber: 93,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 41,
    endStep: 45,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.98,
    serverTimestamp: 1787652479050,
  },
  {
    frameId: 'frame_94',
    turnNumber: 94,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 42,
    endStep: 47,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.25,
    serverTimestamp: 1787652480050,
  },
  {
    frameId: 'frame_95',
    turnNumber: 95,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 43,
    endStep: 49,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.29,
    serverTimestamp: 1787652481050,
  },
  {
    frameId: 'frame_96',
    turnNumber: 96,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 44,
    endStep: 45,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.94,
    serverTimestamp: 1787652482050,
  },
  {
    frameId: 'frame_97',
    turnNumber: 97,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 45,
    endStep: 47,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.44,
    serverTimestamp: 1787652483050,
  },
  {
    frameId: 'frame_98',
    turnNumber: 98,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 46,
    endStep: 49,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.51,
    serverTimestamp: 1787652484050,
  },
  {
    frameId: 'frame_99',
    turnNumber: 99,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 47,
    endStep: 51,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.43,
    serverTimestamp: 1787652485050,
  },
  {
    frameId: 'frame_100',
    turnNumber: 100,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 48,
    endStep: 1,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.45,
    serverTimestamp: 1787652486050,
  },
  {
    frameId: 'frame_101',
    turnNumber: 101,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 49,
    endStep: 3,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.61,
    serverTimestamp: 1787652487050,
  },
  {
    frameId: 'frame_102',
    turnNumber: 102,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 50,
    endStep: 51,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.40,
    serverTimestamp: 1787652488050,
  },
  {
    frameId: 'frame_103',
    turnNumber: 103,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 51,
    endStep: 1,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.52,
    serverTimestamp: 1787652489050,
  },
  {
    frameId: 'frame_104',
    turnNumber: 104,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 0,
    endStep: 3,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 3.27,
    serverTimestamp: 1787652490050,
  },
  {
    frameId: 'frame_105',
    turnNumber: 105,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 1,
    endStep: 5,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.79,
    serverTimestamp: 1787652491050,
  },
  {
    frameId: 'frame_106',
    turnNumber: 106,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 2,
    endStep: 7,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.04,
    serverTimestamp: 1787652492050,
  },
  {
    frameId: 'frame_107',
    turnNumber: 107,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 3,
    endStep: 9,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.30,
    serverTimestamp: 1787652493050,
  },
  {
    frameId: 'frame_108',
    turnNumber: 108,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 4,
    endStep: 5,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.98,
    serverTimestamp: 1787652494050,
  },
  {
    frameId: 'frame_109',
    turnNumber: 109,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 5,
    endStep: 7,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.16,
    serverTimestamp: 1787652495050,
  },
  {
    frameId: 'frame_110',
    turnNumber: 110,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 6,
    endStep: 9,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.72,
    serverTimestamp: 1787652496050,
  },
  {
    frameId: 'frame_111',
    turnNumber: 111,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 7,
    endStep: 11,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.21,
    serverTimestamp: 1787652497050,
  },
  {
    frameId: 'frame_112',
    turnNumber: 112,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 8,
    endStep: 13,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 3.70,
    serverTimestamp: 1787652498050,
  },
  {
    frameId: 'frame_113',
    turnNumber: 113,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 9,
    endStep: 15,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.60,
    serverTimestamp: 1787652499050,
  },
  {
    frameId: 'frame_114',
    turnNumber: 114,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 10,
    endStep: 11,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.39,
    serverTimestamp: 1787652500050,
  },
  {
    frameId: 'frame_115',
    turnNumber: 115,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 11,
    endStep: 13,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.95,
    serverTimestamp: 1787652501050,
  },
  {
    frameId: 'frame_116',
    turnNumber: 116,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 12,
    endStep: 15,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.08,
    serverTimestamp: 1787652502050,
  },
  {
    frameId: 'frame_117',
    turnNumber: 117,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 13,
    endStep: 17,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 5.48,
    serverTimestamp: 1787652503050,
  },
  {
    frameId: 'frame_118',
    turnNumber: 118,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 14,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.41,
    serverTimestamp: 1787652504050,
  },
  {
    frameId: 'frame_119',
    turnNumber: 119,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 15,
    endStep: 21,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.06,
    serverTimestamp: 1787652505050,
  },
  {
    frameId: 'frame_120',
    turnNumber: 120,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 16,
    endStep: 17,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.36,
    serverTimestamp: 1787652506050,
  },
  {
    frameId: 'frame_121',
    turnNumber: 121,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 17,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.22,
    serverTimestamp: 1787652507050,
  },
  {
    frameId: 'frame_122',
    turnNumber: 122,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 18,
    endStep: 21,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.68,
    serverTimestamp: 1787652508050,
  },
  {
    frameId: 'frame_123',
    turnNumber: 123,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 19,
    endStep: 23,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.97,
    serverTimestamp: 1787652509050,
  },
  {
    frameId: 'frame_124',
    turnNumber: 124,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 20,
    endStep: 25,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.76,
    serverTimestamp: 1787652510050,
  },
  {
    frameId: 'frame_125',
    turnNumber: 125,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 21,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.45,
    serverTimestamp: 1787652511050,
  },
  {
    frameId: 'frame_126',
    turnNumber: 126,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 22,
    endStep: 23,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 4.48,
    serverTimestamp: 1787652512050,
  },
  {
    frameId: 'frame_127',
    turnNumber: 127,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 23,
    endStep: 25,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.56,
    serverTimestamp: 1787652513050,
  },
  {
    frameId: 'frame_128',
    turnNumber: 128,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 24,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.09,
    serverTimestamp: 1787652514050,
  },
  {
    frameId: 'frame_129',
    turnNumber: 129,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 25,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.30,
    serverTimestamp: 1787652515050,
  },
  {
    frameId: 'frame_130',
    turnNumber: 130,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 26,
    endStep: 31,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 2.87,
    serverTimestamp: 1787652516050,
  },
  {
    frameId: 'frame_131',
    turnNumber: 131,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 27,
    endStep: 33,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.11,
    serverTimestamp: 1787652517050,
  },
  {
    frameId: 'frame_132',
    turnNumber: 132,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 28,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.61,
    serverTimestamp: 1787652518050,
  },
  {
    frameId: 'frame_133',
    turnNumber: 133,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 29,
    endStep: 31,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.92,
    serverTimestamp: 1787652519050,
  },
  {
    frameId: 'frame_134',
    turnNumber: 134,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 30,
    endStep: 33,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.93,
    serverTimestamp: 1787652520050,
  },
  {
    frameId: 'frame_135',
    turnNumber: 135,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 31,
    endStep: 35,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.57,
    serverTimestamp: 1787652521050,
  },
  {
    frameId: 'frame_136',
    turnNumber: 136,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 32,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.34,
    serverTimestamp: 1787652522050,
  },
  {
    frameId: 'frame_137',
    turnNumber: 137,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 33,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.27,
    serverTimestamp: 1787652523050,
  },
  {
    frameId: 'frame_138',
    turnNumber: 138,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 34,
    endStep: 35,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.73,
    serverTimestamp: 1787652524050,
  },
  {
    frameId: 'frame_139',
    turnNumber: 139,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 35,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.71,
    serverTimestamp: 1787652525050,
  },
  {
    frameId: 'frame_140',
    turnNumber: 140,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 36,
    endStep: 39,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.82,
    serverTimestamp: 1787652526050,
  },
  {
    frameId: 'frame_141',
    turnNumber: 141,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 37,
    endStep: 41,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.13,
    serverTimestamp: 1787652527050,
  },
  {
    frameId: 'frame_142',
    turnNumber: 142,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 38,
    endStep: 43,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.15,
    serverTimestamp: 1787652528050,
  },
  {
    frameId: 'frame_143',
    turnNumber: 143,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 39,
    endStep: 45,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 5.61,
    serverTimestamp: 1787652529050,
  },
  {
    frameId: 'frame_144',
    turnNumber: 144,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 40,
    endStep: 41,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.89,
    serverTimestamp: 1787652530050,
  },
  {
    frameId: 'frame_145',
    turnNumber: 145,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 41,
    endStep: 43,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.12,
    serverTimestamp: 1787652531050,
  },
  {
    frameId: 'frame_146',
    turnNumber: 146,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 42,
    endStep: 45,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.97,
    serverTimestamp: 1787652532050,
  },
  {
    frameId: 'frame_147',
    turnNumber: 147,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 43,
    endStep: 47,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 5.96,
    serverTimestamp: 1787652533050,
  },
  {
    frameId: 'frame_148',
    turnNumber: 148,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 44,
    endStep: 49,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.40,
    serverTimestamp: 1787652534050,
  },
  {
    frameId: 'frame_149',
    turnNumber: 149,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 45,
    endStep: 51,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.03,
    serverTimestamp: 1787652535050,
  },
  {
    frameId: 'frame_150',
    turnNumber: 150,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 46,
    endStep: 47,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.84,
    serverTimestamp: 1787652536050,
  },
  {
    frameId: 'frame_151',
    turnNumber: 151,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 47,
    endStep: 49,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.93,
    serverTimestamp: 1787652537050,
  },
  {
    frameId: 'frame_152',
    turnNumber: 152,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 48,
    endStep: 51,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.79,
    serverTimestamp: 1787652538050,
  },
  {
    frameId: 'frame_153',
    turnNumber: 153,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 49,
    endStep: 1,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.90,
    serverTimestamp: 1787652539050,
  },
  {
    frameId: 'frame_154',
    turnNumber: 154,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 50,
    endStep: 3,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 5.67,
    serverTimestamp: 1787652540050,
  },
  {
    frameId: 'frame_155',
    turnNumber: 155,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 51,
    endStep: 5,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.16,
    serverTimestamp: 1787652541050,
  },
  {
    frameId: 'frame_156',
    turnNumber: 156,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 0,
    endStep: 1,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 4.94,
    serverTimestamp: 1787652542050,
  },
  {
    frameId: 'frame_157',
    turnNumber: 157,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 1,
    endStep: 3,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.06,
    serverTimestamp: 1787652543050,
  },
  {
    frameId: 'frame_158',
    turnNumber: 158,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 2,
    endStep: 5,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.79,
    serverTimestamp: 1787652544050,
  },
  {
    frameId: 'frame_159',
    turnNumber: 159,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 3,
    endStep: 7,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.83,
    serverTimestamp: 1787652545050,
  },
  {
    frameId: 'frame_160',
    turnNumber: 160,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 4,
    endStep: 9,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.45,
    serverTimestamp: 1787652546050,
  },
  {
    frameId: 'frame_161',
    turnNumber: 161,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 5,
    endStep: 11,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.77,
    serverTimestamp: 1787652547050,
  },
  {
    frameId: 'frame_162',
    turnNumber: 162,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 6,
    endStep: 7,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.08,
    serverTimestamp: 1787652548050,
  },
  {
    frameId: 'frame_163',
    turnNumber: 163,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 7,
    endStep: 9,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.01,
    serverTimestamp: 1787652549050,
  },
  {
    frameId: 'frame_164',
    turnNumber: 164,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 8,
    endStep: 11,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.80,
    serverTimestamp: 1787652550050,
  },
  {
    frameId: 'frame_165',
    turnNumber: 165,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 9,
    endStep: 13,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.82,
    serverTimestamp: 1787652551050,
  },
  {
    frameId: 'frame_166',
    turnNumber: 166,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 10,
    endStep: 15,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.75,
    serverTimestamp: 1787652552050,
  },
  {
    frameId: 'frame_167',
    turnNumber: 167,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 11,
    endStep: 17,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.84,
    serverTimestamp: 1787652553050,
  },
  {
    frameId: 'frame_168',
    turnNumber: 168,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 12,
    endStep: 13,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 3.18,
    serverTimestamp: 1787652554050,
  },
  {
    frameId: 'frame_169',
    turnNumber: 169,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 13,
    endStep: 15,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 4.17,
    serverTimestamp: 1787652555050,
  },
  {
    frameId: 'frame_170',
    turnNumber: 170,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 14,
    endStep: 17,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.54,
    serverTimestamp: 1787652556050,
  },
  {
    frameId: 'frame_171',
    turnNumber: 171,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 15,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.06,
    serverTimestamp: 1787652557050,
  },
  {
    frameId: 'frame_172',
    turnNumber: 172,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 16,
    endStep: 21,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.77,
    serverTimestamp: 1787652558050,
  },
  {
    frameId: 'frame_173',
    turnNumber: 173,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 17,
    endStep: 23,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.14,
    serverTimestamp: 1787652559050,
  },
  {
    frameId: 'frame_174',
    turnNumber: 174,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 18,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.78,
    serverTimestamp: 1787652560050,
  },
  {
    frameId: 'frame_175',
    turnNumber: 175,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 19,
    endStep: 21,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.15,
    serverTimestamp: 1787652561050,
  },
  {
    frameId: 'frame_176',
    turnNumber: 176,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 20,
    endStep: 23,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.17,
    serverTimestamp: 1787652562050,
  },
  {
    frameId: 'frame_177',
    turnNumber: 177,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 21,
    endStep: 25,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.68,
    serverTimestamp: 1787652563050,
  },
  {
    frameId: 'frame_178',
    turnNumber: 178,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 22,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.91,
    serverTimestamp: 1787652564050,
  },
  {
    frameId: 'frame_179',
    turnNumber: 179,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 23,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.52,
    serverTimestamp: 1787652565050,
  },
  {
    frameId: 'frame_180',
    turnNumber: 180,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 24,
    endStep: 25,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.02,
    serverTimestamp: 1787652566050,
  },
  {
    frameId: 'frame_181',
    turnNumber: 181,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 25,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.78,
    serverTimestamp: 1787652567050,
  },
  {
    frameId: 'frame_182',
    turnNumber: 182,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 26,
    endStep: 29,
    isCaptureEvent: true,
    isHomeEvent: true,
    executionTimeMs: 3.78,
    serverTimestamp: 1787652568050,
  },
  {
    frameId: 'frame_183',
    turnNumber: 183,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 27,
    endStep: 31,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.82,
    serverTimestamp: 1787652569050,
  },
  {
    frameId: 'frame_184',
    turnNumber: 184,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 28,
    endStep: 33,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.83,
    serverTimestamp: 1787652570050,
  },
  {
    frameId: 'frame_185',
    turnNumber: 185,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 29,
    endStep: 35,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.09,
    serverTimestamp: 1787652571050,
  },
  {
    frameId: 'frame_186',
    turnNumber: 186,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 30,
    endStep: 31,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.09,
    serverTimestamp: 1787652572050,
  },
  {
    frameId: 'frame_187',
    turnNumber: 187,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 31,
    endStep: 33,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.45,
    serverTimestamp: 1787652573050,
  },
  {
    frameId: 'frame_188',
    turnNumber: 188,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 32,
    endStep: 35,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.91,
    serverTimestamp: 1787652574050,
  },
  {
    frameId: 'frame_189',
    turnNumber: 189,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 33,
    endStep: 37,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 3.82,
    serverTimestamp: 1787652575050,
  },
  {
    frameId: 'frame_190',
    turnNumber: 190,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 34,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.76,
    serverTimestamp: 1787652576050,
  },
  {
    frameId: 'frame_191',
    turnNumber: 191,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 35,
    endStep: 41,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.82,
    serverTimestamp: 1787652577050,
  },
  {
    frameId: 'frame_192',
    turnNumber: 192,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 36,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.09,
    serverTimestamp: 1787652578050,
  },
  {
    frameId: 'frame_193',
    turnNumber: 193,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 37,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.10,
    serverTimestamp: 1787652579050,
  },
  {
    frameId: 'frame_194',
    turnNumber: 194,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 38,
    endStep: 41,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.95,
    serverTimestamp: 1787652580050,
  },
  {
    frameId: 'frame_195',
    turnNumber: 195,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 39,
    endStep: 43,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 3.91,
    serverTimestamp: 1787652581050,
  },
  {
    frameId: 'frame_196',
    turnNumber: 196,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 40,
    endStep: 45,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.10,
    serverTimestamp: 1787652582050,
  },
  {
    frameId: 'frame_197',
    turnNumber: 197,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 41,
    endStep: 47,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.04,
    serverTimestamp: 1787652583050,
  },
  {
    frameId: 'frame_198',
    turnNumber: 198,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 42,
    endStep: 43,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.76,
    serverTimestamp: 1787652584050,
  },
  {
    frameId: 'frame_199',
    turnNumber: 199,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 43,
    endStep: 45,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.04,
    serverTimestamp: 1787652585050,
  },
  {
    frameId: 'frame_200',
    turnNumber: 200,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 44,
    endStep: 47,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.58,
    serverTimestamp: 1787652586050,
  },
  {
    frameId: 'frame_201',
    turnNumber: 201,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 45,
    endStep: 49,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.76,
    serverTimestamp: 1787652587050,
  },
  {
    frameId: 'frame_202',
    turnNumber: 202,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 46,
    endStep: 51,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.46,
    serverTimestamp: 1787652588050,
  },
  {
    frameId: 'frame_203',
    turnNumber: 203,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 47,
    endStep: 1,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.72,
    serverTimestamp: 1787652589050,
  },
  {
    frameId: 'frame_204',
    turnNumber: 204,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 48,
    endStep: 49,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.63,
    serverTimestamp: 1787652590050,
  },
  {
    frameId: 'frame_205',
    turnNumber: 205,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 49,
    endStep: 51,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.98,
    serverTimestamp: 1787652591050,
  },
  {
    frameId: 'frame_206',
    turnNumber: 206,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 50,
    endStep: 1,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.71,
    serverTimestamp: 1787652592050,
  },
  {
    frameId: 'frame_207',
    turnNumber: 207,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 51,
    endStep: 3,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.30,
    serverTimestamp: 1787652593050,
  },
  {
    frameId: 'frame_208',
    turnNumber: 208,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 0,
    endStep: 5,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 2.69,
    serverTimestamp: 1787652594050,
  },
  {
    frameId: 'frame_209',
    turnNumber: 209,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 1,
    endStep: 7,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.72,
    serverTimestamp: 1787652595050,
  },
  {
    frameId: 'frame_210',
    turnNumber: 210,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 2,
    endStep: 3,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.92,
    serverTimestamp: 1787652596050,
  },
  {
    frameId: 'frame_211',
    turnNumber: 211,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 3,
    endStep: 5,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.78,
    serverTimestamp: 1787652597050,
  },
  {
    frameId: 'frame_212',
    turnNumber: 212,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 4,
    endStep: 7,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.08,
    serverTimestamp: 1787652598050,
  },
  {
    frameId: 'frame_213',
    turnNumber: 213,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 5,
    endStep: 9,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.84,
    serverTimestamp: 1787652599050,
  },
  {
    frameId: 'frame_214',
    turnNumber: 214,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 6,
    endStep: 11,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.15,
    serverTimestamp: 1787652600050,
  },
  {
    frameId: 'frame_215',
    turnNumber: 215,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 7,
    endStep: 13,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.42,
    serverTimestamp: 1787652601050,
  },
  {
    frameId: 'frame_216',
    turnNumber: 216,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 8,
    endStep: 9,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.46,
    serverTimestamp: 1787652602050,
  },
  {
    frameId: 'frame_217',
    turnNumber: 217,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 9,
    endStep: 11,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.83,
    serverTimestamp: 1787652603050,
  },
  {
    frameId: 'frame_218',
    turnNumber: 218,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 10,
    endStep: 13,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.98,
    serverTimestamp: 1787652604050,
  },
  {
    frameId: 'frame_219',
    turnNumber: 219,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 11,
    endStep: 15,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.91,
    serverTimestamp: 1787652605050,
  },
  {
    frameId: 'frame_220',
    turnNumber: 220,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 12,
    endStep: 17,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.71,
    serverTimestamp: 1787652606050,
  },
  {
    frameId: 'frame_221',
    turnNumber: 221,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 13,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 4.54,
    serverTimestamp: 1787652607050,
  },
  {
    frameId: 'frame_222',
    turnNumber: 222,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 14,
    endStep: 15,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.89,
    serverTimestamp: 1787652608050,
  },
  {
    frameId: 'frame_223',
    turnNumber: 223,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 15,
    endStep: 17,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.60,
    serverTimestamp: 1787652609050,
  },
  {
    frameId: 'frame_224',
    turnNumber: 224,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 16,
    endStep: 19,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.07,
    serverTimestamp: 1787652610050,
  },
  {
    frameId: 'frame_225',
    turnNumber: 225,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 17,
    endStep: 21,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.74,
    serverTimestamp: 1787652611050,
  },
  {
    frameId: 'frame_226',
    turnNumber: 226,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 18,
    endStep: 23,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.54,
    serverTimestamp: 1787652612050,
  },
  {
    frameId: 'frame_227',
    turnNumber: 227,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 19,
    endStep: 25,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.80,
    serverTimestamp: 1787652613050,
  },
  {
    frameId: 'frame_228',
    turnNumber: 228,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 20,
    endStep: 21,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.32,
    serverTimestamp: 1787652614050,
  },
  {
    frameId: 'frame_229',
    turnNumber: 229,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 21,
    endStep: 23,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.79,
    serverTimestamp: 1787652615050,
  },
  {
    frameId: 'frame_230',
    turnNumber: 230,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 22,
    endStep: 25,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.27,
    serverTimestamp: 1787652616050,
  },
  {
    frameId: 'frame_231',
    turnNumber: 231,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 23,
    endStep: 27,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 3.33,
    serverTimestamp: 1787652617050,
  },
  {
    frameId: 'frame_232',
    turnNumber: 232,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 24,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.03,
    serverTimestamp: 1787652618050,
  },
  {
    frameId: 'frame_233',
    turnNumber: 233,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 25,
    endStep: 31,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.41,
    serverTimestamp: 1787652619050,
  },
  {
    frameId: 'frame_234',
    turnNumber: 234,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 26,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 4.62,
    serverTimestamp: 1787652620050,
  },
  {
    frameId: 'frame_235',
    turnNumber: 235,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 27,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.10,
    serverTimestamp: 1787652621050,
  },
  {
    frameId: 'frame_236',
    turnNumber: 236,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 28,
    endStep: 31,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.68,
    serverTimestamp: 1787652622050,
  },
  {
    frameId: 'frame_237',
    turnNumber: 237,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 29,
    endStep: 33,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.68,
    serverTimestamp: 1787652623050,
  },
  {
    frameId: 'frame_238',
    turnNumber: 238,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 30,
    endStep: 35,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 5.02,
    serverTimestamp: 1787652624050,
  },
  {
    frameId: 'frame_239',
    turnNumber: 239,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 31,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.81,
    serverTimestamp: 1787652625050,
  },
  {
    frameId: 'frame_240',
    turnNumber: 240,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 32,
    endStep: 33,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.34,
    serverTimestamp: 1787652626050,
  },
  {
    frameId: 'frame_241',
    turnNumber: 241,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 33,
    endStep: 35,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.66,
    serverTimestamp: 1787652627050,
  },
  {
    frameId: 'frame_242',
    turnNumber: 242,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 34,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.43,
    serverTimestamp: 1787652628050,
  },
  {
    frameId: 'frame_243',
    turnNumber: 243,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 35,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.48,
    serverTimestamp: 1787652629050,
  },
  {
    frameId: 'frame_244',
    turnNumber: 244,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 36,
    endStep: 41,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.42,
    serverTimestamp: 1787652630050,
  },
  {
    frameId: 'frame_245',
    turnNumber: 245,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 37,
    endStep: 43,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 3.44,
    serverTimestamp: 1787652631050,
  },
  {
    frameId: 'frame_246',
    turnNumber: 246,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 38,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.13,
    serverTimestamp: 1787652632050,
  },
  {
    frameId: 'frame_247',
    turnNumber: 247,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 39,
    endStep: 41,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 1.92,
    serverTimestamp: 1787652633050,
  },
  {
    frameId: 'frame_248',
    turnNumber: 248,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 40,
    endStep: 43,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.54,
    serverTimestamp: 1787652634050,
  },
  {
    frameId: 'frame_249',
    turnNumber: 249,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 41,
    endStep: 45,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.88,
    serverTimestamp: 1787652635050,
  },
  {
    frameId: 'frame_250',
    turnNumber: 250,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 42,
    endStep: 47,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.79,
    serverTimestamp: 1787652636050,
  },
  {
    frameId: 'frame_251',
    turnNumber: 251,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 43,
    endStep: 49,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.80,
    serverTimestamp: 1787652637050,
  },
  {
    frameId: 'frame_252',
    turnNumber: 252,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 44,
    endStep: 45,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 5.77,
    serverTimestamp: 1787652638050,
  },
  {
    frameId: 'frame_253',
    turnNumber: 253,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 45,
    endStep: 47,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.44,
    serverTimestamp: 1787652639050,
  },
  {
    frameId: 'frame_254',
    turnNumber: 254,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 46,
    endStep: 49,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.41,
    serverTimestamp: 1787652640050,
  },
  {
    frameId: 'frame_255',
    turnNumber: 255,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 47,
    endStep: 51,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.68,
    serverTimestamp: 1787652641050,
  },
  {
    frameId: 'frame_256',
    turnNumber: 256,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 48,
    endStep: 1,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.12,
    serverTimestamp: 1787652642050,
  },
  {
    frameId: 'frame_257',
    turnNumber: 257,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 49,
    endStep: 3,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.83,
    serverTimestamp: 1787652643050,
  },
  {
    frameId: 'frame_258',
    turnNumber: 258,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 50,
    endStep: 51,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.87,
    serverTimestamp: 1787652644050,
  },
  {
    frameId: 'frame_259',
    turnNumber: 259,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 51,
    endStep: 1,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.40,
    serverTimestamp: 1787652645050,
  },
  {
    frameId: 'frame_260',
    turnNumber: 260,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 0,
    endStep: 3,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 4.98,
    serverTimestamp: 1787652646050,
  },
  {
    frameId: 'frame_261',
    turnNumber: 261,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 1,
    endStep: 5,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.25,
    serverTimestamp: 1787652647050,
  },
  {
    frameId: 'frame_262',
    turnNumber: 262,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 2,
    endStep: 7,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.69,
    serverTimestamp: 1787652648050,
  },
  {
    frameId: 'frame_263',
    turnNumber: 263,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 3,
    endStep: 9,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.12,
    serverTimestamp: 1787652649050,
  },
  {
    frameId: 'frame_264',
    turnNumber: 264,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 4,
    endStep: 5,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.40,
    serverTimestamp: 1787652650050,
  },
  {
    frameId: 'frame_265',
    turnNumber: 265,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 5,
    endStep: 7,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.64,
    serverTimestamp: 1787652651050,
  },
  {
    frameId: 'frame_266',
    turnNumber: 266,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 6,
    endStep: 9,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.65,
    serverTimestamp: 1787652652050,
  },
  {
    frameId: 'frame_267',
    turnNumber: 267,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 7,
    endStep: 11,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.17,
    serverTimestamp: 1787652653050,
  },
  {
    frameId: 'frame_268',
    turnNumber: 268,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 8,
    endStep: 13,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.33,
    serverTimestamp: 1787652654050,
  },
  {
    frameId: 'frame_269',
    turnNumber: 269,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 9,
    endStep: 15,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.34,
    serverTimestamp: 1787652655050,
  },
  {
    frameId: 'frame_270',
    turnNumber: 270,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 10,
    endStep: 11,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.60,
    serverTimestamp: 1787652656050,
  },
  {
    frameId: 'frame_271',
    turnNumber: 271,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 11,
    endStep: 13,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.60,
    serverTimestamp: 1787652657050,
  },
  {
    frameId: 'frame_272',
    turnNumber: 272,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 12,
    endStep: 15,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.42,
    serverTimestamp: 1787652658050,
  },
  {
    frameId: 'frame_273',
    turnNumber: 273,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 13,
    endStep: 17,
    isCaptureEvent: true,
    isHomeEvent: true,
    executionTimeMs: 4.52,
    serverTimestamp: 1787652659050,
  },
  {
    frameId: 'frame_274',
    turnNumber: 274,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 14,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.90,
    serverTimestamp: 1787652660050,
  },
  {
    frameId: 'frame_275',
    turnNumber: 275,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 15,
    endStep: 21,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.30,
    serverTimestamp: 1787652661050,
  },
  {
    frameId: 'frame_276',
    turnNumber: 276,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 16,
    endStep: 17,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.41,
    serverTimestamp: 1787652662050,
  },
  {
    frameId: 'frame_277',
    turnNumber: 277,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 17,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.26,
    serverTimestamp: 1787652663050,
  },
  {
    frameId: 'frame_278',
    turnNumber: 278,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 18,
    endStep: 21,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.08,
    serverTimestamp: 1787652664050,
  },
  {
    frameId: 'frame_279',
    turnNumber: 279,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 19,
    endStep: 23,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.24,
    serverTimestamp: 1787652665050,
  },
  {
    frameId: 'frame_280',
    turnNumber: 280,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 20,
    endStep: 25,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 5.38,
    serverTimestamp: 1787652666050,
  },
  {
    frameId: 'frame_281',
    turnNumber: 281,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 21,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.80,
    serverTimestamp: 1787652667050,
  },
  {
    frameId: 'frame_282',
    turnNumber: 282,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 22,
    endStep: 23,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.65,
    serverTimestamp: 1787652668050,
  },
  {
    frameId: 'frame_283',
    turnNumber: 283,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 23,
    endStep: 25,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.85,
    serverTimestamp: 1787652669050,
  },
  {
    frameId: 'frame_284',
    turnNumber: 284,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 24,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.78,
    serverTimestamp: 1787652670050,
  },
  {
    frameId: 'frame_285',
    turnNumber: 285,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 25,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.33,
    serverTimestamp: 1787652671050,
  },
  {
    frameId: 'frame_286',
    turnNumber: 286,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 26,
    endStep: 31,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 4.10,
    serverTimestamp: 1787652672051,
  },
  {
    frameId: 'frame_287',
    turnNumber: 287,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 27,
    endStep: 33,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 4.51,
    serverTimestamp: 1787652673051,
  },
  {
    frameId: 'frame_288',
    turnNumber: 288,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 28,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.54,
    serverTimestamp: 1787652674051,
  },
  {
    frameId: 'frame_289',
    turnNumber: 289,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 29,
    endStep: 31,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.57,
    serverTimestamp: 1787652675051,
  },
  {
    frameId: 'frame_290',
    turnNumber: 290,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 30,
    endStep: 33,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.54,
    serverTimestamp: 1787652676051,
  },
  {
    frameId: 'frame_291',
    turnNumber: 291,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 31,
    endStep: 35,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.03,
    serverTimestamp: 1787652677051,
  },
  {
    frameId: 'frame_292',
    turnNumber: 292,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 32,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.05,
    serverTimestamp: 1787652678051,
  },
  {
    frameId: 'frame_293',
    turnNumber: 293,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 33,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.51,
    serverTimestamp: 1787652679051,
  },
  {
    frameId: 'frame_294',
    turnNumber: 294,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 34,
    endStep: 35,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.82,
    serverTimestamp: 1787652680051,
  },
  {
    frameId: 'frame_295',
    turnNumber: 295,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 35,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.57,
    serverTimestamp: 1787652681051,
  },
  {
    frameId: 'frame_296',
    turnNumber: 296,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 36,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.73,
    serverTimestamp: 1787652682051,
  },
  {
    frameId: 'frame_297',
    turnNumber: 297,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 37,
    endStep: 41,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.97,
    serverTimestamp: 1787652683051,
  },
  {
    frameId: 'frame_298',
    turnNumber: 298,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 38,
    endStep: 43,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.62,
    serverTimestamp: 1787652684051,
  },
  {
    frameId: 'frame_299',
    turnNumber: 299,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 39,
    endStep: 45,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 5.26,
    serverTimestamp: 1787652685051,
  },
  {
    frameId: 'frame_300',
    turnNumber: 300,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 40,
    endStep: 41,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.41,
    serverTimestamp: 1787652686051,
  },
  {
    frameId: 'frame_301',
    turnNumber: 301,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 41,
    endStep: 43,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.93,
    serverTimestamp: 1787652687051,
  },
  {
    frameId: 'frame_302',
    turnNumber: 302,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 42,
    endStep: 45,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.48,
    serverTimestamp: 1787652688051,
  },
  {
    frameId: 'frame_303',
    turnNumber: 303,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 43,
    endStep: 47,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.64,
    serverTimestamp: 1787652689051,
  },
  {
    frameId: 'frame_304',
    turnNumber: 304,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 44,
    endStep: 49,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.45,
    serverTimestamp: 1787652690051,
  },
  {
    frameId: 'frame_305',
    turnNumber: 305,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 45,
    endStep: 51,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.19,
    serverTimestamp: 1787652691051,
  },
  {
    frameId: 'frame_306',
    turnNumber: 306,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 46,
    endStep: 47,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.43,
    serverTimestamp: 1787652692051,
  },
  {
    frameId: 'frame_307',
    turnNumber: 307,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 47,
    endStep: 49,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.39,
    serverTimestamp: 1787652693051,
  },
  {
    frameId: 'frame_308',
    turnNumber: 308,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 48,
    endStep: 51,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.37,
    serverTimestamp: 1787652694051,
  },
  {
    frameId: 'frame_309',
    turnNumber: 309,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 49,
    endStep: 1,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.73,
    serverTimestamp: 1787652695051,
  },
  {
    frameId: 'frame_310',
    turnNumber: 310,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 50,
    endStep: 3,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.93,
    serverTimestamp: 1787652696051,
  },
  {
    frameId: 'frame_311',
    turnNumber: 311,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 51,
    endStep: 5,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.45,
    serverTimestamp: 1787652697051,
  },
  {
    frameId: 'frame_312',
    turnNumber: 312,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 0,
    endStep: 1,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 5.89,
    serverTimestamp: 1787652698051,
  },
  {
    frameId: 'frame_313',
    turnNumber: 313,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 1,
    endStep: 3,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.59,
    serverTimestamp: 1787652699051,
  },
  {
    frameId: 'frame_314',
    turnNumber: 314,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 2,
    endStep: 5,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.87,
    serverTimestamp: 1787652700051,
  },
  {
    frameId: 'frame_315',
    turnNumber: 315,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 3,
    endStep: 7,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.03,
    serverTimestamp: 1787652701051,
  },
  {
    frameId: 'frame_316',
    turnNumber: 316,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 4,
    endStep: 9,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.19,
    serverTimestamp: 1787652702051,
  },
  {
    frameId: 'frame_317',
    turnNumber: 317,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 5,
    endStep: 11,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.39,
    serverTimestamp: 1787652703051,
  },
  {
    frameId: 'frame_318',
    turnNumber: 318,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 6,
    endStep: 7,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.16,
    serverTimestamp: 1787652704051,
  },
  {
    frameId: 'frame_319',
    turnNumber: 319,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 7,
    endStep: 9,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.69,
    serverTimestamp: 1787652705051,
  },
  {
    frameId: 'frame_320',
    turnNumber: 320,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 8,
    endStep: 11,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.67,
    serverTimestamp: 1787652706051,
  },
  {
    frameId: 'frame_321',
    turnNumber: 321,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 9,
    endStep: 13,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.16,
    serverTimestamp: 1787652707051,
  },
  {
    frameId: 'frame_322',
    turnNumber: 322,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 10,
    endStep: 15,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.51,
    serverTimestamp: 1787652708051,
  },
  {
    frameId: 'frame_323',
    turnNumber: 323,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 11,
    endStep: 17,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.50,
    serverTimestamp: 1787652709051,
  },
  {
    frameId: 'frame_324',
    turnNumber: 324,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 12,
    endStep: 13,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.68,
    serverTimestamp: 1787652710051,
  },
  {
    frameId: 'frame_325',
    turnNumber: 325,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 13,
    endStep: 15,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 2.29,
    serverTimestamp: 1787652711051,
  },
  {
    frameId: 'frame_326',
    turnNumber: 326,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 14,
    endStep: 17,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.91,
    serverTimestamp: 1787652712051,
  },
  {
    frameId: 'frame_327',
    turnNumber: 327,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 15,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.99,
    serverTimestamp: 1787652713051,
  },
  {
    frameId: 'frame_328',
    turnNumber: 328,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 16,
    endStep: 21,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.17,
    serverTimestamp: 1787652714051,
  },
  {
    frameId: 'frame_329',
    turnNumber: 329,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 17,
    endStep: 23,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 1.61,
    serverTimestamp: 1787652715051,
  },
  {
    frameId: 'frame_330',
    turnNumber: 330,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 18,
    endStep: 19,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.09,
    serverTimestamp: 1787652716051,
  },
  {
    frameId: 'frame_331',
    turnNumber: 331,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 19,
    endStep: 21,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.07,
    serverTimestamp: 1787652717051,
  },
  {
    frameId: 'frame_332',
    turnNumber: 332,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 20,
    endStep: 23,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.42,
    serverTimestamp: 1787652718051,
  },
  {
    frameId: 'frame_333',
    turnNumber: 333,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 21,
    endStep: 25,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.21,
    serverTimestamp: 1787652719051,
  },
  {
    frameId: 'frame_334',
    turnNumber: 334,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 22,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.58,
    serverTimestamp: 1787652720051,
  },
  {
    frameId: 'frame_335',
    turnNumber: 335,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 23,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 2.25,
    serverTimestamp: 1787652721051,
  },
  {
    frameId: 'frame_336',
    turnNumber: 336,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 24,
    endStep: 25,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 4.38,
    serverTimestamp: 1787652722051,
  },
  {
    frameId: 'frame_337',
    turnNumber: 337,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 25,
    endStep: 27,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.91,
    serverTimestamp: 1787652723051,
  },
  {
    frameId: 'frame_338',
    turnNumber: 338,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 26,
    endStep: 29,
    isCaptureEvent: false,
    isHomeEvent: true,
    executionTimeMs: 5.71,
    serverTimestamp: 1787652724051,
  },
  {
    frameId: 'frame_339',
    turnNumber: 339,
    activeColor: 'BLUE',
    diceRoll: 4,
    tokenId: 'BLUE_3',
    startStep: 27,
    endStep: 31,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 5.93,
    serverTimestamp: 1787652725051,
  },
  {
    frameId: 'frame_340',
    turnNumber: 340,
    activeColor: 'RED',
    diceRoll: 5,
    tokenId: 'RED_0',
    startStep: 28,
    endStep: 33,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.71,
    serverTimestamp: 1787652726051,
  },
  {
    frameId: 'frame_341',
    turnNumber: 341,
    activeColor: 'GREEN',
    diceRoll: 6,
    tokenId: 'GREEN_1',
    startStep: 29,
    endStep: 35,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.51,
    serverTimestamp: 1787652727051,
  },
  {
    frameId: 'frame_342',
    turnNumber: 342,
    activeColor: 'YELLOW',
    diceRoll: 1,
    tokenId: 'YELLOW_2',
    startStep: 30,
    endStep: 31,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.78,
    serverTimestamp: 1787652728051,
  },
  {
    frameId: 'frame_343',
    turnNumber: 343,
    activeColor: 'BLUE',
    diceRoll: 2,
    tokenId: 'BLUE_3',
    startStep: 31,
    endStep: 33,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 2.40,
    serverTimestamp: 1787652729051,
  },
  {
    frameId: 'frame_344',
    turnNumber: 344,
    activeColor: 'RED',
    diceRoll: 3,
    tokenId: 'RED_0',
    startStep: 32,
    endStep: 35,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.06,
    serverTimestamp: 1787652730051,
  },
  {
    frameId: 'frame_345',
    turnNumber: 345,
    activeColor: 'GREEN',
    diceRoll: 4,
    tokenId: 'GREEN_1',
    startStep: 33,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.38,
    serverTimestamp: 1787652731051,
  },
  {
    frameId: 'frame_346',
    turnNumber: 346,
    activeColor: 'YELLOW',
    diceRoll: 5,
    tokenId: 'YELLOW_2',
    startStep: 34,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.74,
    serverTimestamp: 1787652732051,
  },
  {
    frameId: 'frame_347',
    turnNumber: 347,
    activeColor: 'BLUE',
    diceRoll: 6,
    tokenId: 'BLUE_3',
    startStep: 35,
    endStep: 41,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 1.25,
    serverTimestamp: 1787652733051,
  },
  {
    frameId: 'frame_348',
    turnNumber: 348,
    activeColor: 'RED',
    diceRoll: 1,
    tokenId: 'RED_0',
    startStep: 36,
    endStep: 37,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 3.59,
    serverTimestamp: 1787652734051,
  },
  {
    frameId: 'frame_349',
    turnNumber: 349,
    activeColor: 'GREEN',
    diceRoll: 2,
    tokenId: 'GREEN_1',
    startStep: 37,
    endStep: 39,
    isCaptureEvent: false,
    isHomeEvent: false,
    executionTimeMs: 4.39,
    serverTimestamp: 1787652735051,
  },
  {
    frameId: 'frame_350',
    turnNumber: 350,
    activeColor: 'YELLOW',
    diceRoll: 3,
    tokenId: 'YELLOW_2',
    startStep: 38,
    endStep: 41,
    isCaptureEvent: true,
    isHomeEvent: false,
    executionTimeMs: 4.41,
    serverTimestamp: 1787652736051,
  },
];
