import { ShopItem } from '../types/shop.js';

export const CATALOG_SHOP_ITEMS: ShopItem[] = [
  // Board Themes
  {
    id: 'theme_classic',
    name: 'Classic Wooden Board',
    description: 'Timeless traditional wooden ludo layout.',
    category: 'BOARD_THEME',
    price: 0,
    currency: 'COINS',
    imageUrl: '/assets/images/themes/classic.jpg',
    assetKey: 'CLASSIC',
    previewColors: ['#E74C3C', '#2ECC71', '#F1C40F', '#3498DB'],
  },
  {
    id: 'theme_neon',
    name: 'Cyber Neon Arena',
    description: 'Futuristic glowing neon board with cybernetic grid lines.',
    category: 'BOARD_THEME',
    price: 5000,
    currency: 'COINS',
    imageUrl: '/assets/images/themes/neon.jpg',
    assetKey: 'NEON',
    previewColors: ['#FF0055', '#00FF66', '#FFE600', '#00CCFF'],
  },
  {
    id: 'theme_royal',
    name: 'Royal Palace Gold',
    description: 'Luxurious velvet and solid gold ornate board theme.',
    category: 'BOARD_THEME',
    price: 250,
    currency: 'GEMS',
    imageUrl: '/assets/images/themes/royal.jpg',
    assetKey: 'ROYAL',
    previewColors: ['#D4AF37', '#800020', '#4B0082', '#0047AB'],
  },
  {
    id: 'theme_ice',
    name: 'Frost & Glacial Ice',
    description: 'Sub-zero frozen ice cavern board with crystalline effects.',
    category: 'BOARD_THEME',
    price: 8000,
    currency: 'COINS',
    imageUrl: '/assets/images/themes/ice.jpg',
    assetKey: 'ICE',
    previewColors: ['#A5F3FC', '#06B6D4', '#0284C7', '#38BDF8'],
  },
  // Token Skins
  {
    id: 'token_standard',
    name: 'Standard Pawn',
    description: 'Traditional solid color pawns.',
    category: 'TOKEN_SKIN',
    price: 0,
    currency: 'COINS',
    imageUrl: '/assets/images/tokens/standard.png',
    assetKey: 'STANDARD',
  },
  {
    id: 'token_dragon',
    name: 'Draconic Crest Tokens',
    description: 'Finely carved dragon pawns with glowing eyes.',
    category: 'TOKEN_SKIN',
    price: 3000,
    currency: 'COINS',
    imageUrl: '/assets/images/tokens/dragon.png',
    assetKey: 'DRAGON',
  },
  {
    id: 'token_crystal',
    name: 'Prismatic Crystal Shards',
    description: 'Translucent gemstone pawns with glowing light refraction.',
    category: 'TOKEN_SKIN',
    price: 150,
    currency: 'GEMS',
    imageUrl: '/assets/images/tokens/crystal.png',
    assetKey: 'CRYSTAL',
  },
  // Dice Skins
  {
    id: 'dice_classic',
    name: 'Classic White Ivory',
    description: 'Standard ivory dice with black pips.',
    category: 'DICE_SKIN',
    price: 0,
    currency: 'COINS',
    imageUrl: '/assets/images/dice/classic.png',
    assetKey: 'CLASSIC',
  },
  {
    id: 'dice_gold',
    name: 'Solid 24k Gold Dice',
    description: 'Heavy gold dice with diamond inlaid pips.',
    category: 'DICE_SKIN',
    price: 100,
    currency: 'GEMS',
    imageUrl: '/assets/images/dice/gold.png',
    assetKey: 'GOLD',
  },
];
